### PR TITLE
KEYCLOAK-9383 Fixing broken link to EAP Configuration Guide

### PR DESCRIPTION
**Pull request by andymunro**
@stian Can you check this fixed the broken link?

### CODE REVIEW

**Comment by andymunro** [comment]
@Stian Can you check this fixed so we can merge this change?

**Review by stianst — CHANGES_REQUESTED** [review]
This will break for community as it's missing appserver_config_guide_link variable in community. It's also hardcoding the name to JBoss EAP guide, which needs to be WildFly in community.

**Review by stianst — CHANGES_REQUESTED** [review]
Should not use if blocks, but rather just templated links and names for the links. See https://raw.githubusercontent.com/keycloak/keycloak-documentation/0c427ffea17bf46e6ecfd3a8722b53ec07573b3b/server_installation/topics/network/bind-address.adoc as an example.

**Comment by andymunro** [comment]
@stianst You are right. I could set up a variable for Securing a cluster with different definitions in the community versus product template files.  However, on further inspection, I don’t see this topic covered in the WildFly documentation.  I looked in the HA guide which has some of the same content as the EAP Config guide, but it's not there. It's not in the Security Guide either. Do you know if it exists somewhere?

**Comment by andymunro** [comment]
@stianst This is where I would expect to find securing a cluster information for WildFly: https://docs.wildfly.org/18/High_Availability_Guide.html#JGroups_Subsystem

I don't see it anywhere.  The reference from the SSO guide is not a requirement.  Do you think we need it for the Keycloak version?

**Comment by stianst** [comment]
@sebastienblanc do you know where community docs for securing JGroups on WildFly can be found?

**Comment by sebastienblanc** [comment]
@stianst TBH I have no idea :) but I can try to ask around

**Comment by stianst** [comment]
@sebastienblanc hehe, wrong Sebi ;)

@slaskawi how about you? Do you know any community docs for enabling security on JGroups?

**Comment by andymunro** [comment]
@stianst, @slaskawi I have not had any feedback.

In the SSO Guide, the reference to the EAP guide is not to a required procedure.  I propose that we include the reference for SSO and exclude it for Keycloak.

**Review by slaskawi — APPROVED** [review]

**Comment by andymunro** [comment]
Thanks for approving this @slaskawi.  However, the change I made points to the WildFly High Availability Guide (https://docs.wildfly.org/18/High_Availability_Guide.html#JGroups_Subsystem) for people who want to enable authentication and encryption for clustering communication.  However, I don't see that information there, so I think I should remove that reference.

**Review by stianst — APPROVED** [review]

**Pull request merged**
