### PR TITLE
Updating OpenShift instructions

### LINKED ISSUE #1465: Updating OpenShift instructions to add a SAN when creating a self-signed certificate
### Description

The Openshift describe a process of creation a self-signed certificate process without defining a SAN. This results in an error. 

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Adding a SAN to a self-signed certificate procedure

Close #1465

### CODE REVIEW

**Comment by andymunro** [comment]
@pskopek, @pzaoral  Can you verify this update?

**Comment by Pepo48** [comment]
@andymunro LGTM. Thanks!

**Review by pdrozd — APPROVED** [review]
Approving based on pzaoral approve

**Review by pedroigor — APPROVED** [review]

**Comment by andymunro** [comment]
@abstractj Can you merge this PR, which approved by QE and development?

**Comment by andymunro** [comment]
Thanks, @abstractj

**Pull request merged**
