### PR TITLE
Support for acr in keycloak.js

### PR DESCRIPTION
**Pull request by mposolda**
Closes #10154

### CODE REVIEW

**Comment by mposolda** [comment]
@jonkoops @andymunro Do you please have a chance to review?

**Comment by mposolda** [comment]
Corresponding codebase PR: https://github.com/keycloak/keycloak-documentation/pull/1420

**Review by jonkoops — APPROVED** [review]
Looks good from my perspective.

**Review by andymunro — APPROVED** [review]

**Comment by mposolda** [comment]
@jonkoops @andymunro Thanks

**Pull request merged**
