### PR TITLE
KEYCLOAK-13240 Reinstating missing section

### PR DESCRIPTION
**Pull request by andymunro**
@stianst I found the missing section and reinstated it.

### CODE REVIEW

**Comment by stianst** [comment]
I'm not really sure if this section should be reintroduced. Don't know why it was removed in the first place, but I would assume it was intentional.

**Review by stianst — CHANGES_REQUESTED** [review]
We need to identify why this section was removed in the first place. There was probably a reason for it.

**Comment by andymunro** [comment]
Is there a way to see if  PR was issued when this was removed?   Here is the source I found in the history: https://github.com/keycloak/keycloak-documentation/blob/081f1c9903173d3287d1a8e7dcac20a9e6cc61f0/server_installation/topics/clustering/sticky-sessions.adoc
Do you think we should just close this request?

**Comment by stianst** [comment]
So here's the commit it was removed in:
https://github.com/keycloak/keycloak-documentation/commit/692ccf82d63d0512be3b0820ee2d2f063f220ecc

Which leads to this JIRA:
https://issues.redhat.com/browse/KEYCLOAK-8300

@mposolda Can you remember why this section was removed?

**Comment by mposolda** [comment]
@stianst @andymunro Yes, this section was removed intentionally. AFAIR the reasons were discussed and they were:
- mod_cluster is not very used loadbalancer and the mod_cluster project is only in the maintenance mode AFAIR
- We had hard times with make mod_cluster loadbalancer working when upgrading to Wildfly 14. In general, the configuration of mod_cluster subsystem changed quite often and was quite fragile during every Wildfly upgrade. Also we're not testing with mod_cluster, so there was an additional cost with having this configuration up-to-date.

So my vote is to close the KEYCLOAK-13240 as rejected.

We already have some example setup in the clustering chapter, which use the other loadbalancer, so there is no need another section specific to mod_cluster IMO. See https://www.keycloak.org/docs/latest/server_installation/index.html#using-the-built-in-load-balancer . However when looking into this, I see that this example is using domain mode and I am sure that this is the setup, which we don't test. So it's possible that this docs can become out-of-date (or maybe already is out-of-date)... :/

**Comment by stianst** [comment]
Makes sense, closing this PR and the JIRA

**Pull request closed without merging**
