### PR TITLE
Extend documentation for password reset.

### PR DESCRIPTION
**Pull request by CollinAlpert**
I accidentally closed the initial PR due to merge conflicts: https://github.com/keycloak/keycloak-documentation/pull/1412
@ahus1

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for the PR. I ask @andymunro, our technical writer on the team, for a quick review. 

Ideally a PR would contain only one commit. For this PR, I'll ask the committers if they could squash it on merge. If you want to give it a try to squash the commits yourself before Andrew does the review, please do so (but that's optional).

**Comment by CollinAlpert** [comment]
Let's do the squash merge.

**Review by andymunro — APPROVED** [review]

**Comment by ahus1** [comment]
Dear maintainers, please squash-and-merge this PR. Thanks!

**Review by ahus1 — APPROVED** [review]
Thank you for this PR!

**Review by stianst — APPROVED** [review]

**Pull request merged**
