### PR TITLE
Release Notes need Known Issues

### PR DESCRIPTION
**Pull request by matthewhelmke**
I'm including a small number of formatting improvements and phrasing edits here, but really this PR is intended to include the Known Issues, as soon as I have them.

### CODE REVIEW

**Comment by matthewhelmke** [comment]
Added a commit with content from #550, which I am closing.

**Comment by matthewhelmke** [comment]
Anybody have a current subscription and able to see this URL? @stianst 

https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=core.service.rhsso

It is found in the file /getting_started/topics/distribution-files-product.adoc and is causing the Travis build failure. I cannot view it when I log in as I apparently don't have a subscription. Even after logging in with my account I get: https://access.redhat.com/403

**Comment by matthewhelmke** [comment]
The known issues have been added. Requesting final approval from the product manager before merging.

**Review by hmlnarik — APPROVED** [review]

**Comment by hmlnarik** [comment]
Approving based on RHSSO-1685 comment

**Pull request merged**
