### PR TITLE
KEYCLOAK-8146 Document the LocaleSelectorSPI for server development

### PR DESCRIPTION
**Pull request by knutz3n**

### CODE REVIEW

**Comment by knutz3n** [comment]
The build is broken because openid.net has been moved from http to https.
Please review https://github.com/keycloak/keycloak-documentation/pull/470.
I will update this PR as soon as the build is stable.

**Review by matthewhelmke — APPROVED** [review]
This is great, thank you! For docs, we have two reviews: one from me from a technical writing standpoint and a second from engineering to double-check the details. Once both are complete we look for an appropriate time to merge. Thank you for helping out!

**Comment by knutz3n** [comment]
Thanks for the review. Please note that the documentation is documenting a new feature which is implemented with PR https://github.com/keycloak/keycloak/pull/5504 and Jira https://issues.jboss.org/browse/KEYCLOAK-8146. So the implementation should probably be merged before the documentation is updated.

**Comment by matthewhelmke** [comment]
Excellent. I have added the "Merge with Code" label to help us (on our end) remember that.

**Review by mposolda — APPROVED** [review]
@knutz3n @matthewhelmke Thanks!

**Pull request merged**
