### PR TITLE
KEYCLOAK-8227 Remove offending endif

### PR DESCRIPTION
**Pull request by hmlnarik**

### CODE REVIEW

**Review by matthewhelmke — DISMISSED** [review]
LGTM, thank you.

**Comment by hmlnarik** [comment]
@matthewhelmke Part of this issue was fixed in https://github.com/keycloak/keycloak-documentation/commit/b6f053a34e5795058d90965ecc0777998a985fb1 (which also caused conflicts), could you please reapprove?

**Review by matthewhelmke — APPROVED** [review]
Thank you, @hmlnarik

**Comment by hmlnarik** [comment]
Looks like the issue is not fixed, the build fails randomly after few restarts. Hence cancelling this PR.

**Pull request closed without merging**
