### PR TITLE
RHSSO-1197 fix rpm adapter names for eap6

### PR DESCRIPTION
**Pull request by alicerum**

### CODE REVIEW

**Comment by matthewhelmke** [comment]
Thank you, @wyvie . I appreciate the correction!

**Comment by alicerum** [comment]
Don't merge yet, please. It's still in discussion.

**Comment by alicerum** [comment]
It's okay to merge, names will not change in the foreseeable future.

**Comment by stianst** [comment]
I think the names will change as they will have the RHSSO version in them. @pskopek ?

**Comment by pskopek** [comment]
we are going to have new adapter package names as follows:
keycloak-adapter-sso7_2 (jb-eap-7.1-rhel-7)
keycloak-adapter (jb-eap-7.1-rhel-7)
keycloak-adapter-sso7_2-eap6 (jb-eap-6.4-rhel-6)

**Comment by stianst** [comment]
@wyvie can you update this PR with those names or should I open a new one?

**Comment by alicerum** [comment]
I can update here, no problems, but..
What's the difference between `keycloak-adapter-sso7_2` and `keycloak-adapter`?
Why is `7_2` part of the package name?
What will be the name for saml adapter?
Why do we find out about all those changes in documentation pull request or from repo search?
It's the third (if not fourth) package names' change I'm aware of, and all those differently named packages are lying across the repos. Users might be confused, because I definitely am.
Who's the person to discuss those changes with?

**Comment by stianst** [comment]
@wyvie  talk to @pskopek he knows the details

**Comment by stianst** [comment]
Closing this as the names are being updated in https://github.com/keycloak/keycloak-documentation/pull/264

**Pull request closed without merging**
