### PR TITLE
KEYCLOAK-5574 Added edit this page on GitHub link

### PR DESCRIPTION
**Pull request by stianst**

### CODE REVIEW

**Review by matthewhelmke — DISMISSED** [review]
I am looking forward to seeing this in action!

**Comment by stianst** [comment]
@matthewhelmke should be ready to go now, can you check it out locally and try to build docs to make sure it's all working for you

**Comment by matthewhelmke** [comment]
@stianst Perhaps I did something wrong. After checking out locally and building with "mvn clean install", I see the two new links in the API Documentation page, where they function as expected, but I don't see them in any of the other pages.

**Comment by stianst** [comment]
There should be links on the beginning of each included file. Like this https://keycloak-docs.github.io/deploy-docs-pullrequest/PR/326/server_installation/index.html.

**Comment by matthewhelmke** [comment]
Found the problem. If you have your browser window set too narrow, you don't see the links. I maximized the browser window and the links are there.

**Comment by stianst** [comment]
Will try to tweak the styles a bit to make it work better on a narrow screen

**Comment by stianst** [comment]
@matthewhelmke position tweaked to work better with all screen resolutions

**Comment by matthewhelmke** [comment]
@stianst fetching and building now

**Comment by matthewhelmke** [comment]
@stianst That is working well for me now. Thanks.

**Review by sebastienblanc — APPROVED** [review]
:+1:

**Pull request merged**
