### PR TITLE
KEYCLOAK-16784 Correction command to say private key not certificate.

### PR DESCRIPTION
**Pull request by andymunro**
@iankko Can you verify this correction?

### CODE REVIEW

**Review by iankko — DISMISSED** [review]
LGTM, thanks @andymunro (but someone else needs to merge it).

Verification step(s):
```
$ keytool -genkeypair -keyalg RSA -keysize 2048 -dname "CN=secure-sso-sso-app-demo.openshift.example.com" -alias jboss -keystore keystore.jks
Enter keystore password:  
Re-enter new password: 
```

```
$ keytool -list -keystore keystore.jks 
Enter keystore password:  
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

jboss, Oct 6, 2021, PrivateKeyEntry, 
Certificate fingerprint (SHA-256): A0:1C:9E:E5:8F:9D:EF:6B:70:13:75:59:A9:A1:5B:6A:1C:D0:BB:24:9A:E3:36:8E:01:6F:5D:E3:65:0B:AD:E9
```

Note: When creating the documention, the error was probably caused by copy & paste description from the previous step.

@orivat Great catch, thx for reporting the issue!

**Comment by iankko** [comment]
@pskopek @mposolda Can you possibly help us with merging this one? (as for the change itself, it LGTM AFAICT. See above).

**Comment by andymunro** [comment]
@abstractj Would you be able to merge this very small change that @iankko has approved?

**Comment by andymunro** [comment]
@pedroigor Would you have time to merge this very minor change?

**Review by mposolda — APPROVED** [review]
@iankko @andymunro Thanks! Sorry I missed this in queue of other PRs.

**Comment by pedroigor** [comment]
@andymunro Sorry, too late :)

**Comment by andymunro** [comment]
Thanks, @mposolda and @pedroigor.

**Pull request merged**
