### PR TITLE
KEYCLOAK-17089

### PR DESCRIPTION
**Pull request by Sascha-Block**
Related to KEYCLOAK-17089

### CODE REVIEW

**Review by Gamerdachs — APPROVED** [review]

**Comment by stianst** [comment]
Thanks, did you see this issue when using an old version of Java?

We could just set those properties in the parent POM I'd say, rather than documenting a work-around like you've done here.

**Comment by Sascha-Block** [comment]
it should be clarified in the documentations could occur, and yes those properties should be defined in the parent POM

**Comment by stianst** [comment]
Closing this as it should be fixed in quickstarts directly, we shouldn't have a workaround in the docs here.

**Comment by Sascha-Block** [comment]
@stianst Simply closing tickets and issues isn't a solution or even progress for a project.

**Comment by stianst** [comment]
@Sascha-Block this PR is invalid, and the issue it refers to has been closed with a proper fix:

https://github.com/keycloak/keycloak-quickstarts/blob/b1e556e52472e60f527c5610106507e791cc48ac/pom.xml#L73-L74

So, not really sure what the problem is?

**Pull request closed without merging**
