### PR TITLE
KEYCLOAK-10837 Add possibility to disable certificate verification for outgoing https connections

### PR DESCRIPTION
**Pull request by ykvasetskiy**

### CODE REVIEW

**Comment by ykvasetskiy** [comment]
@stianst Code was merged in https://github.com/keycloak/keycloak/pull/6169
This is follow-up documentation for that pull request.

**Comment by lrozenblyum** [comment]
The code was already merged in 8.0.0. Probably the label 'Merge with Code' may be removed. @stianst

**Comment by lrozenblyum** [comment]
Any chance to merge this improvement to the documentation @stianst ?

**Comment by stianst** [comment]
@abstractj code changes was merged without doc changes. Can you review this asap?

**Comment by abstractj** [comment]
@stianst sure, will do

**Review by abstractj — APPROVED** [review]

**Pull request merged**
