### PR TITLE
KEYCLOAK-6126 update RPM version numbers

### PR DESCRIPTION
**Pull request by matthewhelmke**
Updated all occurrences of JBoss EAP 7.0 and RH-SSO 7.1 to EAP 7.1 and RH-SSO 7.2.
Updated the repository for rh-sso 7.2 to rh-sso-7.2-for-rhel-<RHEL-VERSION>-server-rpms.
Updated the repository for EAP to jb-eap-7.1-for-rhel-<RHEL-VERSION>-server-rpms.

### CODE REVIEW

**Comment by stianst** [comment]
There's {project_versionDoc} and {appserver_version} which should be used instead of adding the versions directly into the doc.

Just sent PR to update appserver_version here https://github.com/keycloak/keycloak-documentation/pull/282

**Comment by matthewhelmke** [comment]
Excellent! Thank you. I'll update the other PR with a commit shortly.

**Comment by matthewhelmke** [comment]
The local build would not parse variables in the two subscription manager lines, so there are still versions hard-coded in two places.

**Comment by stianst** [comment]
It should do if you wrap subscription manager lines in a source block:

    [source,bash,subs="attributes+"]
    ----
    subscription-manager repos --enable=jb-eap-7.1-for-rhel-{project_versionDoc}-server-rpms
    ----

**Comment by matthewhelmke** [comment]
I'll test that out and make a new commit (or comment if I can't get it working).

**Comment by matthewhelmke** [comment]
Worked well, thanks!

**Pull request merged**
