### PR TITLE
docs(server-admin): Documenting OIDC user session note mappers

### PR DESCRIPTION
**Pull request by shousper**
Related: https://github.com/keycloak/keycloak/pull/5096

- Documents new and existing OIDC user session note mappers.

### CODE REVIEW

**Comment by wvdhaute** [comment]
Maybe add the following notes also while you are at it?

- identity_provider = Idp used
- identity_provider_identity = IdP username

**Comment by shousper** [comment]
@wvdhaute Sorry, I've had to remove IdP related fields. Just trying to get my PR over the line..

**Comment by mposolda** [comment]
@sshousper Looks great, Thanks! Just one minor thing: Could you squash the commits into single commit instead of 2 commits and ensure that this commit has JIRA ID in it? See https://github.com/keycloak/keycloak/blob/master/CONTRIBUTING.md#submitting-your-pr

**Review by pnagesha — CHANGES_REQUESTED** [review]
Q: What are “These” via mappers or user session details? I am assuming it is the user session details and here are my suggested edits:

User session details are via mappers and depend on various criteria. User session details are automatically included  when you use or enable a feature on a client. You can also click the Add builtin button to include session details.
Impersonated user sessions provide the following details:
    • IMPERSONATOR_ID: The ID of an impersonating user
    • IMPERSONATOR_USERNAME: The username of an impersonating user
Service account sessions provide the following details:
    • clientId : The client ID of the service account
    • ClientAddress : The remote host IP of the service account authenticated device
    • clientHost:  The remote host name of the service account authenticated device

**Comment by mposolda** [comment]
@shousper Thanks for squasing the commits. Could you please improve wording a bit as @pnagesha suggested?

**Pull request merged**
