### PR TITLE
KEYCLOAK-14265 Typos in Authentication part of Keycloak Documentation

### PR DESCRIPTION
**Pull request by drichtarik**

### CODE REVIEW

**Comment by mposolda** [comment]
@drichtarik Could you please create JIRA and squash the commits? Otherwise LGTM

**Comment by drichtarik** [comment]
@mposolda done

**Review by mposolda — APPROVED** [review]
@drichtarik Thanks!

@andymunro Do you have a chance to review this please?

**Comment by stianst** [comment]
@mposolda FIY We don't need JIRA for small updates like this to the docs.

**Pull request merged**
