### PR TITLE
KEYCLOAK-7166 Added documentation of the initiating_idp-parameter.

### PR DESCRIPTION
**Pull request by torbjornsk**

### CODE REVIEW

**Review by matthewhelmke — DISMISSED** [review]
Thank you for this submission. I am the one who approves text from a writing standpoint. Someone from the engineering team will take a look at this and review it from their perspective. If all goes well, we will then be able to merge.

**Comment by mposolda** [comment]
@torbjornsk It's good to have the content in the logout.adoc file, but IMO will be good to have something in the identity brokering documentation too and somehow cross-reference it to the logout.adoc paragraph you created. 

Identity Brokering Documentation seems to be the first place where people, who deals with identityBrokering issues, will look first. How about creating new short section "Identity Broker Logout" inside the identityBroker chapter and just mention something like:
Usually when logout from the ${project.name} is triggered, the Keycloak will send request to the external identity providers, who were used for login user to Keycloak, and user will be logged-out from this identity provider too. It is possible to skip this behaviour (See <link-to-logout.adoc-page for more details)

**Comment by torbjornsk** [comment]
Added a new section about identity broker logout.

**Comment by torbjornsk** [comment]
Hmm, the build failed with or without my newest changes, so tried to rebase against upstream/master. I did the following:

- git fetch upstream
- git rebase upstream/master
- git push --> failed because my current branch was behind the remote
- git pull --> got a merge commit
- git push

Now it seems my branch is all messed up. Don't really know why, as it shouldn't contain anything not already in upstream/master (except my changes).

**Comment by mposolda** [comment]
Closing as there is no more feedback. Feel free to re-open once you manage to clean/rebase this PR to have just single commit on the top of latest master.

**Comment by torbjornsk** [comment]
@mposolda @matthewhelmke I've added a new, clean PR with the same changes here: https://github.com/keycloak/keycloak-documentation/pull/510

Hopefully it can be merged before I need to merge from master again :)

**Comment by matthewhelmke** [comment]
@torbjornsk Thank you. I'll take a look now.

**Pull request closed without merging**
