### PR TITLE
declarative-user-profile for read only attributes

### PR DESCRIPTION
**Pull request by bastianccm**
Rename legacy-user-profile to declarative-user-profile in read only attribute documentation.

### CODE REVIEW

**Review by andymunro — DISMISSED** [review]

**Comment by bastianccm** [comment]
Hey @stianst @andymunro do I have to do anything to get this merged?

**Comment by andymunro** [comment]
@bastianccm The checks are not completing
Have you tried this command: git pull upstream main

**Comment by bastianccm** [comment]
Hi @andymunro the checks are pending, I don't know how I can trigger them? I rebased anyway, hope this helps.
@keycloak-docs-bot reports them to be successful.

**Comment by andymunro** [comment]
Okay, I think then it's up to @stianst to merge it.

**Comment by pedroigor** [comment]
@bastianccm The documentation you are changing is indeed for legacy. Although you can use that property with declarative too.

For the declarative provider, we want people using the read-only capabilities from the user profile configuration and not using the "old" way of setting read-only attributes.

Does it make sense for you?

**Comment by bastianccm** [comment]
@pedroigor I do understand, but from what I can tell the user profile configuration is not yet enabled by default, is that correct?
https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/Profile.java#L67

Of course the setting does not work for quarkus either, but for everyone using up to Keycloak 16, the legacy setting does not have an effect anymore, from what I understand, fixing that was my intentation.

But feel free to close this if it's not making sense to update this part of the documentation anymore.

**Comment by pedroigor** [comment]
> @pedroigor I do understand, but from what I can tell the user profile configuration is not yet enabled by default, is that correct? https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/Profile.java#L67
> 

Yes, it is not. But the configuration can also be set to the declarative provider (the still preview feature).

> Of course the setting does not work for quarkus either, but for everyone using up to Keycloak 16, the legacy setting does not have an effect anymore, from what I understand, fixing that was my intentation.
> 

It works for the new dist too but uses a different format. The documentation is updated now to show this new format. 

We still have the same providers (legacy and declarative) in the new dist. And the legacy is still the default.

> But feel free to close this if it's not making sense to update this part of the documentation anymore.

Thanks, I appreciate your time on it.

**Comment by bastianccm** [comment]
@pedroigor thanks for reviewing and clarifying!

**Pull request closed without merging**
