### PR TITLE
Update install-client-adapter.adoc

### PR DESCRIPTION
**Pull request by dreamcrash**
Duplicated steps

### CODE REVIEW

**Comment by manishbansal8843** [comment]
Wow what are the odds that after 20 hours, i landed up on the same page raised a PR #996 to fix it.

**Review by ASzc — APPROVED** [review]
They're not exact duplicates:

```diff
--- /tmp/a	2020-07-27 10:12:14.643497678 -0600
+++ /tmp/b	2020-07-27 10:09:05.772746640 -0600
@@ -26,19 +26,19 @@
 +
 [NOTE]
 ====
-If you receive a `file not found`, make sure that you used `unzip` in the previous step.  This method of extraction installs the files in the right place.
+If you receive a `file not found`, make sure you used `unzip` in the previous step.  This method of extraction installs the files in the right place.
 ====
 
 ifeval::[{project_product}==true]
 +
-.Linux/Unix
+.EAP 7.3 on Linux/Unix
 [source,bash,subs=+attributes]
 ----
 $ ./jboss-cli.sh --file=adapter-elytron-install-offline.cli
 ----
 
 +
-.Windows
+.EAP 7.3 on Windows
 [source,bash,subs=+attributes]
 ----
 > jboss-cli.bat --file=adapter-elytron-install-offline.cli
```

According to git blame, the duplicated instructions, and also the differences above, came from the same commit (a3004ea). I can't tell why this is exactly, it seems like it was a different draft that was left in somehow.

Since this PR deletes the what looks to be the inferior version, seems good.

**Comment by ASzc** [comment]
@abstractj LGTM

**Comment by abstractj** [comment]
@dreamcrash could you please rebase?

**Comment by dreamcrash** [comment]
Yes, sure I just did it.

**Pull request closed without merging**
