### PR TITLE
KEYCLOAK-8857 Update the `Using Spring Boot Configuration` section

### PR DESCRIPTION
**Pull request by little-pinecone**
* update bean declaration example to explicitly show that it should be declared in a class separate to `KeycloakWebSecurityConfigurerAdapter`
* add explanation to possible `Circular References` problem in Spring Boot 2.6+
* remove unnecessary whitespace
* update is connected with the [#8857](https://github.com/keycloak/keycloak/issues/8857) keycloak issue

### CODE REVIEW

**Comment by andymunro** [comment]
@little-pinecone To fix the waiting for status message, use this command:  git pull upstream main

**Review by andymunro — APPROVED** [review]

**Comment by little-pinecone** [comment]
@andymunro I ran the `git pull upstream main` command and it didn't change the "waiting for status" message. I don't see any merge commits in the repository and the branch doesn't have any conflicts with `main` so rebasing/merging shouldn't be needed.

Maybe the reason is that the workflows need to be approved and run, like described in [Approving workflow runs from public forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)?

**Review by ahus1 — APPROVED** [review]
Thank you for this PR, looks good to me.

I'll ask the maintainers to approve the GitHub action run.

**Review by mhajas — APPROVED** [review]
Approving per @ahus1 's approval

**Pull request merged**
