### PR TITLE
KEYCLOAK-13561 adding a reminder to set temporary password

### PR DESCRIPTION
**Pull request by andymunro**
Adding a statement about making the password temporary

### CODE REVIEW

**Comment by andymunro** [comment]
@pskopek Actually, the Jira reference is for SSO.   The Keycloak jira is https://issues.redhat.com/browse/KEYCLOAK-14154

**Comment by andymunro** [comment]
@lhanusov  Does this look okay?

**Review by lhanusov — APPROVED** [review]
Yes, thank you Andy @andymunro.

**Comment by andymunro** [comment]
@abstractj This is merged for downstream.  Can you merge it for upstream?

**Review by abstractj — APPROVED** [review]

**Comment by abstractj** [comment]
@pskopek @andymunro approved, so you guys can decide what to do next.

**Comment by andymunro** [comment]
@pskopek  Who can merge this for upnstream. It is merged downstream.

**Comment by andymunro** [comment]
This was already merged by a different PR.
See https://github.com/keycloak/keycloak-documentation/blob/master/openshift/topics/tutorials.adoc

**Comment by andymunro** [comment]
This was already merged by a different PR.
See https://github.com/keycloak/keycloak-documentation/blob/master/openshift/topics/tutorials.adoc

**Comment by andymunro** [comment]
This was already merged by a different PR.
See https://github.com/keycloak/keycloak-documentation/blob/master/openshift/topics/tutorials.adoc

**Comment by andymunro** [comment]
This was already merged by a different PR.
See https://github.com/keycloak/keycloak-documentation/blob/master/openshift/topics/tutorials.adoc

**Comment by andymunro** [comment]
This was already merged by a different PR.
See https://github.com/keycloak/keycloak-documentation/blob/master/openshift/topics/tutorials.adoc

**Pull request closed without merging**
