### PR TITLE
Updating Server Admin guide for new Admin Console

### LINKED ISSUE #1575: Update Server Administration Guide for new Admin Console
### Description

Revise procedures, screen shots, and field definitions to reflect the new Admin Console for Keycloak 19.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Close #1575

### CODE REVIEW

**Comment by andymunro** [comment]
@edewit @ssilvert Can you check these updates to the OIDC section?
​We will need 2 updated screen shots for SAML and OIDC.
The SAML section will still need some other changes to match the sequence of the fields for creating a SAML client.
I will work on that next week after we are done with RHSSO 7.6

**Comment by ssilvert** [comment]
> @edewit @ssilvert Can you check these updates to the OIDC section?​We will need 2 updated screen shots for SAML and OIDC. The SAML section will still need some other changes to match the sequence of the fields for creating a SAML client. I will work on that next week after we are done with RHSSO 7.6

@andymunro Can you be a little more specific about what you want me to do?  282 files are changed in this PR.

**Comment by andymunro** [comment]
@ssilvert This PR contains all other PRs for all the other chapters and those PRs are already approved.  However, I made some more updates to make sure the Clients chapter includes field definitions in the right order.  Since we are not releasing Keycloak 19 this week, we can wait to make some final cleanup.  I am working on GA documentation for SSO 7.6 this week.

**Comment by andymunro** [comment]
I checked failures from the second Keycloak build and it only shows "server-root," which is command line syntax, not a variable.

**Comment by Aboullos** [comment]
LGTM!

**Review by ssilvert — DISMISSED** [review]

**Comment by andymunro** [comment]
Replaced by https://github.com/keycloak/keycloak-documentation/pull/1626

**Pull request closed without merging**
