### PR TITLE
Fix incorrect source format

### PR DESCRIPTION
**Pull request by k-tamura**

### CODE REVIEW

**Review by matthewhelmke — DISMISSED** [review]
Thank you for the fixes! Your attention to detail is very much appreciated.

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
@k-tamura  could you rebase this please?

**Comment by k-tamura** [comment]
Done. Please check again.

**Review by matthewhelmke — APPROVED** [review]
Thank you. LGTM

**Pull request merged**
