### PR TITLE
 KEYCLOAK-8571 added a note to leave update password enabled

### PR DESCRIPTION
**Pull request by andymunro**
Added this note for this issue: https://issues.jboss.org/browse/KEYCLOAK-8571

### CODE REVIEW

**Review by iankko — DISMISSED** [review]
@andymunro Should this be `WARNING:` rather than a `NOTE:` (Or maybe even `CAUTION:`)? Other than that, LGTM.

**Review by iankko — DISMISSED** [review]
LGTM

**Review by hmlnarik — APPROVED** [review]

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Please squash the commits into a single one that has KEYCLOAK JIRA in the title

**Review by abstractj — DISMISSED** [review]

**Comment by hmlnarik** [comment]
@andymunro I had been too quick with my previous comment, let me provide more details.

The PR needs to specify Keycloak JIRA by prefixing the PR title as well as the commit message with `KEYCLOAK-nnnn` key (to have backports to z-stream maintainable). To do this, you need to do the following in your `password` branch:
1. `git rebase -i HEAD~2` (see [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) for the details what does it
2. within the rebase, use `pick` or `p` for  first commit and `fixup` or `f` for the second
3. then you can use `git commit --amend` to amend the commit message
4. finally you force push this `password` branch to your github repository: `git push -f`

The steps 2-3 can be simplified by using `reword` type instead of `pick`. See https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history for more details.

Hope that helps.

**Review by iankko — DISMISSED** [review]
LGTM

**Review by hmlnarik — CHANGES_REQUESTED** [review]
Please remove unrelated change in topics/templates/document-attributes-community.adoc.

This should work (writing from top of my head so some typos possible):
1. Switch to the `password` branch
2. `git checkout HEAD^ topics/templates/document-attributes-community.adoc.` (see [here](https://stackoverflow.com/questions/54350240/can-git-checkout-head-file-revert-a-file-in-a-commit) for more info)
3. `git commit --amend` and push as before

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
