### PR TITLE
KEYCLOAK-17924 CIBA feature misplaced in documentation

### PR DESCRIPTION
**Pull request by vanrar68**
Prevent CIBA entry and WebAuthN entry to get mixed up

### CODE REVIEW

**Comment by vanrar68** [comment]
@mposolda @tnorimat Not sure this is the right thing. CIBA entry shows up at the right place but it seems the WebAuthN entry is now gone...
Not an asciidoc specialist, seems to be related to the ifeval clause for the webauthn entry

**Comment by vanrar68** [comment]
> @mposolda @tnorimat Not sure this is the right thing. CIBA entry shows up at the right place but it seems the WebAuthN entry is now gone...
> Not an asciidoc specialist, seems to be related to the ifeval clause for the webauthn entry

Or maybe everything is just fine, I can't access the documentation compiled by keycloak-docs-bot so let's wait...

**Comment by tnorimat** [comment]
@vanrar68 By looking at https://keycloak-docs.github.io/deploy-docs-pullrequest/PR/1164/server_installation/index.html , it works well. Thank you.

**Comment by vanrar68** [comment]
> @vanrar68 By looking at https://keycloak-docs.github.io/deploy-docs-pullrequest/PR/1164/server_installation/index.html , it works well. Thank you.

Yes, thanks, tagging as ready for review now

**Review by mposolda — APPROVED** [review]
@vanrar68 @tnorimat Thanks!

**Pull request merged**
