### PR TITLE
Deprecate `podDisruptionBudget`

### LINKED ISSUE #551: Deprecate `podDisruptionBudget`
### Description

* Make sure the Operator ignores the `podDisruptionBudget` field when running on K8s >=1.25.
* Deprecate the `podDisruptionBudget` field in the docs.

### Discussion

_No response_

### Motivation

K8s 1.25 is removing some APIs. One of them is [PodDisruptionBudget v1beta1](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) that is [used](https://github.com/keycloak/keycloak-operator/blob/e99da8a15034acd1fef1fdf2e43d99efe81914f3/pkg/model/pod_disruption_budget.go) by the Operator.

### Details

_No response_

### PR DESCRIPTION
**Pull request by vmuzikar**
Closes https://github.com/keycloak/keycloak-operator/issues/551

### CODE REVIEW

**Review by andymunro — DISMISSED** [review]
Looks good, @vmuzikar. Let me know when it is merged so I can backport it to RH SSO for 7.6.

**Comment by andymunro** [comment]
@abstractj Can you merge this, so I can then backport for SSO 7.6 which is due to GA next week?

**Comment by abstractj** [comment]
@vmuzikar @andymunro could you please rebase and solve the git conflicts?

**Comment by vmuzikar** [comment]
@abstractj Thanks, rebased.

**Review by andymunro — COMMENTED** [review]
Looks good, @vmuzikar

**Review by andymunro — APPROVED** [review]

**Pull request merged**
