### PR TITLE
Matthew Helmke edits for Red Hat writing assessment

### PR DESCRIPTION
**Pull request by matthewhelmke**
I have not read any style guide in use for files in the repo, so I made a decision that could be controversial along with the text edits. Specifically, I chose to narrow the margins within the file for easier viewing while editing across all text editors. The right margin does not affect the Markdown processors  I have used, all of which ignore CRs and format text into paragraphs based on an empty white line. I hope that is also the case here with asciidoc.

Other changes include:
* Removing double spaces between sentences
* Changing passive voice to active
* Expanding the reasoning given for limiting use of the master realm
* Changing some phrasing in favor of expressions that I thought sounded closer to a standard in technical documentation, such as replacing "king of all realms" to "the highest level in the hierarchy of realms"

### CODE REVIEW

**Comment by patriot1burke** [comment]
If you want to do minor things like reducing line columns, then please do that sort of stuff in a separate PR.  Its often hard to distinguish actual edits from formatting.

BTW, why are you removing double spaces between sentences?  That's something I learned back in type class in high school and is pretty much a standard in any book you read.

**Comment by matthewhelmke** [comment]
Your comment on the reduction of columns in a separate PR is quite reasonable. I'll keep that in mind for the future.

One space following a period at the end of a sentence is the standard and has been for years, although those of use who learned to type using actual typewriters (including myself) were taught to use two spaces. So, the thought is a reasonable one. In the digital era, spacing is dealt with by typesetting software, not manually. The extra space is not needed and can cause problems in some circumstances. [https://www.google.com/search?q=how+many+spaces+after+a+period](https://www.google.com/search?q=how+many+spaces+after+a+period).

From the IBM Style Guide, page 59: "Use a period at the end of a sentence. After a period, use the spacing that your authoring tool provides. If you insert spacing manually, insert only one space after a period." Other common/major style guides and manuals concur, such as:
- [The Microsoft Manual of Style](https://www.safaribooksonline.com/library/view/microsoft-manual-of/9780735669833/ch09s01.html)
- [The Chicago Manual of Style](http://www.chicagomanualofstyle.org/qanda/data/faq/topics/OneSpaceorTwo.html)
- [The Modern Language Association MLA Handbook](https://style.mla.org/2016/07/27/number-of-spaces-after-period/)

**Comment by stianst** [comment]
@matthewhelmke an early welcome to team Keycloak :)

**Comment by matthewhelmke** [comment]
Thank you, @stianst!

**Comment by stianst** [comment]
Changes looks good to me, except "Red Hat recommends" part. I don't think we should state that in the community/Keycloak version of the docs.

**Comment by matthewhelmke** [comment]
Sounds good. I'll update momentarily.

**Comment by stianst** [comment]
Thanks

**Pull request merged**
