### PR TITLE
Fix link to token exchange spec

### PR DESCRIPTION
**Pull request by stianst**

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
Looks good to me. If we want perfection, the link ends up redirecting from HTTP to HTTPS, so we could also add the s to both links.

**Comment by mposolda** [comment]
@stianst @matthewhelmke I've actually did the same thing in the morning, just added also 's' to the links to avoid redirecting to HTTPS as Matthew mentioned. Looks we can close this?

**Comment by mposolda** [comment]
Jira is: https://issues.jboss.org/browse/KEYCLOAK-6353

**Comment by matthewhelmke** [comment]
Yes, @mposolda did this in #298, which I already merged. Closing this issue.

**Pull request closed without merging**
