### PR TITLE
KEYCLOAK-14139 Upgrade login screen to PF4 docs

### PR DESCRIPTION
**Pull request by mabartos**
JIRA: [KEYCLOAK-14139](https://issues.redhat.com/browse/KEYCLOAK-14139)

### CODE REVIEW

**Review by mposolda — CHANGES_REQUESTED** [review]
@mabartos Thanks for the PR! Maybe it worth to add also a short note to the "Identity providers" for the custom icons possibility, because that is the place where people will look if they are interested in identity providers stuff. Maybe just something like "We have possibility to have custom icons on login screens for each identity provier. For more details, please refer to the "Themes" chapter" . Or something like this :-)

**Comment by mabartos** [comment]
> @mabartos Thanks for the PR! Maybe it worth to add also a short note to the "Identity providers" for the custom icons possibility, because that is the place where people will look if they are interested in identity providers stuff. Maybe just something like "We have possibility to have custom icons on login screens for each identity provier. For more details, please refer to the "Themes" chapter" . Or something like this :-)

Good point! Thanks @mposolda

**Comment by mposolda** [comment]
@mabartos Thanks for the change! However now I see that PR contains changes in 20 files and many image files. I guess this was not intended?

**Comment by mabartos** [comment]
> @mabartos Thanks for the change! However now I see that PR contains changes in 20 files and many image files. I guess this was not intended?

@mposolda It was intended. I've noticed, there are some old screens, so I've updated them to new PF4 design :)

**Review by mposolda — DISMISSED** [review]
@mabartos Ok, Thanks!

**Comment by mposolda** [comment]
@andymunro Do you please have a chance to review this? Thanks!

**Review by mposolda — APPROVED** [review]
@mabartos Thanks for the PR and for fixing all the tests!

@andymunro I am merging this as the related "Codebase" pull request has some other work, which depends on it and will be good to have it in master asap. However if you have a chance to review this and comment here, @mabartos will send follow-up pull request to incorporate your suggestions. Thanks a lot!

**Comment by mposolda** [comment]
Codebase PR: https://github.com/keycloak/keycloak/pull/7470

**Pull request merged**
