### PR TITLE
Updates to Configuring auditing

### LINKED ISSUE #1469: Updating documentation for the new Admin Console
### Description

This guides will be updated to include the new screens, procedures, and field definitions: 

- Server Administration Guide 
- Securing Applications and Services Guide 
- Authorization Services Guide 

### Discussion

https://github.com/keycloak/keycloak/discussions/11205

### Issues
issues exist in this epic for each chapter

**Server Administration Guide**
- https://github.com/keycloak/keycloak-documentation/issues/1482 
- https://github.com/keycloak/keycloak-documentation/issues/1483
- https://github.com/keycloak/keycloak-documentation/issues/1484
- https://github.com/keycloak/keycloak-documentation/issues/1485
- https://github.com/keycloak/keycloak-documentation/issues/1544
- https://github.com/keycloak/keycloak-documentation/issues/1486
- https://github.com/keycloak/keycloak-documentation/issues/1487
- https://github.com/keycloak/keycloak-documentation/issues/1488
- https://github.com/keycloak/keycloak-documentation/issues/1489
- https://github.com/keycloak/keycloak-documentation/issues/1490
- https://github.com/keycloak/keycloak-documentation/issues/1491
- https://github.com/keycloak/keycloak-documentation/issues/1492
- https://github.com/keycloak/keycloak-documentation/issues/1493
- https://github.com/keycloak/keycloak-documentation/issues/1494
- https://github.com/keycloak/keycloak-documentation/issues/1559

**Securing applications and Services Guide**
- https://github.com/keycloak/keycloak-documentation/issues/1495

**Authorization Services Guide**
- https://github.com/keycloak/keycloak-documentation/issues/1496
- https://github.com/keycloak/keycloak-documentation/issues/1497
- https://github.com/keycloak/keycloak-documentation/issues/1498
- https://github.com/keycloak/keycloak-documentation/issues/1499
- https://github.com/keycloak/keycloak-documentation/issues/1500
- https://github.com/keycloak/keycloak-documentation/issues/1501
- https://github.com/keycloak/keycloak-documentation/issues/1502

### Motivation

_No response_

### LINKED ISSUE #1492: Configuring auditing to track events chapter
### Description

Update this Server Administration Guide chapter for the new Admin Console

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
May need a different version to isolate SSO content to separate files

Closes #1492

### CODE REVIEW

**Comment by andymunro** [comment]
@pskopek I created -prod files to keep the old Admin Console/wildfly content, which we will need until SSO 8.0 (RHBK). I am using the existing {project_product} and {project_community} attributes.

At SSO 8.0, we can delete the -prod files because that version will use the new Admin Console and quarkus.

**Comment by pskopek** [comment]
@andymunro the concept looks good to me.

**Comment by andymunro** [comment]
@Aboullos Can you review this chapter, which we discussed in the meeting today?

**Comment by andymunro** [comment]
Closed replace by https://github.com/keycloak/keycloak-documentation/pull/1524

**Pull request closed without merging**
