### PR TITLE
KEYCLOAK-13248 Revising cross DC graphic to use standard formats.

### PR DESCRIPTION
**Pull request by andymunro**
@tkyjovsk I have included the revised Cross DC graphic that Jess created.  Can you take a look?

### CODE REVIEW

**Review by stianst — COMMENTED** [review]
We already have basis for creating diagrams here https://github.com/keycloak/keycloak-misc. This does not follow this standard. This needs to be discussed with the wider team before basically create yet another "theme" for diagrams.

**Comment by andymunro** [comment]
Thanks, Stian.  this is helpful.  We need to be consistent. 

We have our Doc Sync on Wednesday and our graphic artist, Jess Schaefer, can join the call.  Let's focus on graphics in that call.

**Comment by stianst** [comment]
I think we need to have PNG version in images directory, with a separtae place for the SVG. Browser aren't always great at rendering SVGs, so not sure docs should use SVGs when hosted

**Review by stianst — CHANGES_REQUESTED** [review]
SVG should go somewhere else as now it ends up being copied into distributed documentation without being used. The PNG is the same I assume for Keycloak and RH-SSO so should go into shared images directory instead of duplicated.

**Comment by andymunro** [comment]
The PNGs contain icons labelled either Keycloak or RH SSO, so we need to keep them separate.

We can store the SVG elsewhere.  How about:  https://github.com/keycloak/keycloak-misc/tree/master/diagrams ?

**Comment by stianst** [comment]
If images are different then we also need to store the different SVGs, as we need to keep the exact same SVG as was used to produce the PNG

SVGs should be stored within this repo. Perhaps add image-sources to the root of this repo?

**Comment by andymunro** [comment]
@stianst Okay, that makes sense.  So are you suggesting I create an images-sources folder at the root of the keycloak-documentation repo?

If so, should both SVGs for Keycloak and RH SSO go there, or should the RH SSO go in the keycloak-documentation-prod repo?

**Comment by stianst** [comment]
Actually thinking some more. Perhaps adding it in a separate place would just make it hard to find. For community docs it wouldn't be a problem to just not copy the SVG into the docs dist, so can just go alongside the PNG. Not sure if that would have any implication on Pantheon/customer portal.

**Comment by andymunro** [comment]
It would not be a problem for Pantheon.  So would you like me to just add the SVG for the RH SSO version in the same place?

**Comment by stianst** [comment]
Yes, please. I can update docs build to filter out SVGs afterwards

**Comment by andymunro** [comment]
@stianst I add two versions of the SVG file in the images directory.  Hope that works.

**Comment by stianst** [comment]
Closing this PR as I've opened a new one here:
https://github.com/keycloak/keycloak-documentation/pull/891

I moved the SVGs so they are in the same location as the PNG, with the same names (except extension). This makes it easier to discover the SVGs.

I've also changed the Keycloak docs build to only include PNGs.

**Pull request closed without merging**
