### PR TITLE
KEYCLOAK-9809 KEYCLOAK-8575 Release note for client authentication in…

### PR DESCRIPTION
**Pull request by mposolda**
… OIDC identity providers

### CODE REVIEW

**Comment by mposolda** [comment]
@andymunro Do you have a chance to review please? Thanks

**Review by andymunro — APPROVED** [review]

**Comment by mposolda** [comment]
@stianst Do you have a chance to review release note? Thanks

**Review by andymunro — DISMISSED** [review]

**Review by stianst — DISMISSED** [review]

**Comment by stianst** [comment]
@mposolda can you resolve conflicts please?

**Comment by mposolda** [comment]
@stianst Conflicts resolved.

**Review by stianst — APPROVED** [review]

**Comment by stianst** [comment]
Merged manually to resolve merge conflicts

**Comment by stianst** [comment]
https://github.com/keycloak/keycloak-documentation/commit/73a9c8af1c7da000a816a4d700434dc397a65523

**Pull request closed without merging**
