### PR TITLE
KEYCLOAK-17022 Fix cross-reference in installation guide.

### PR DESCRIPTION
**Pull request by andymunro**
@sguilhen Can you check this one?

### CODE REVIEW

**Review by sguilhen — APPROVED** [review]

**Comment by stianst** [comment]
Link in community is #_clustering, see https://www.keycloak.org/docs/latest/server_installation/#_clustering

**Comment by andymunro** [comment]
@stianst For some reason, the links in the product don't work with the underscore.  It's not just this link.

**Comment by stianst** [comment]
In this PR you are breaking the Keycloak docs to fix the RH-SSO docs though.

**Comment by andymunro** [comment]
@stianst I am leaving the community attributes definition as #_clustering

**Review by stianst — CHANGES_REQUESTED** [review]
I see the link is only changed in prod docs, but it's not very good to have different links in community/prod here as it makes it harder to maintain. Please add [[_clustering]] to the corresponding header to make the link the same in both versions..

**Comment by stianst** [comment]
Here's a correct fix that leaves the link the same for community and product:
https://github.com/keycloak/keycloak-documentation/pull/1202/files

**Comment by stianst** [comment]
This is a wider problem and there are a number of links to other sections that are broken. Closing this issue and created a wider issue here KEYCLOAK-18408.

**Pull request closed without merging**
