### PR TITLE
Gatekeeper release notes

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by hmlnarik — DISMISSED** [review]

**Review by andymunro — COMMENTED** [review]
should be:  ...when the `Revoke Refresh Token` was enabled on...

**Comment by abstractj** [comment]
@andymunro updated!

**Review by andymunro — CHANGES_REQUESTED** [review]
Hi, I don't see this change implemented:

should be: ...when the Revoke Refresh Token was enabled on...

**Comment by abstractj** [comment]
@andymunro @hmlnarik this PR was superseded by https://github.com/keycloak/keycloak-documentation/pull/707.

**Pull request closed without merging**
