### PR TITLE
KEYCLOAK-14157 Correcting template name and table problem.

### PR DESCRIPTION
**Pull request by andymunro**
The table was not the best option for displaying the needed information.  I replaced the table with command output.
@lhanusov, @pskopek can you verify?

### CODE REVIEW

**Review by lhanusov — APPROVED** [review]
@andymunro I agree with you, LGTM.

**Review by pskopek — APPROVED** [review]

**Comment by andymunro** [comment]
@abstractj This is already merged in downstream: https://github.com/keycloak/keycloak-documentation-prod/pull/164 
Should be merged now in upstream?

**Comment by abstractj** [comment]
@andymunro tests on Travis are failing, which makes @ASzc unhappy because he fixed it some weeks ago. Could you please check the logs?

**Comment by andymunro** [comment]
@abstractj Okay, thanks.  Good point.

**Pull request merged**
