### PR TITLE
KEYCLOAK-11918 Add latest and archive builds to documentation

### PR DESCRIPTION
**Pull request by stianst**

### CODE REVIEW

**Review by abstractj — DISMISSED** [review]

**Review by hmlnarik — DISMISSED** [review]
Looks good to me, thanks. Personally I'd prefer version and link to "latest" being visible in the top bar, rather than in individual guide titles. From my POV, this is not a blocker from merging this as is though.

**Comment by stianst** [comment]
@hmlnarik Me too, but not sure I can get that to work. Top-bar is static html at the moment + there's not really any room. Will give it a little go and see if I can get something working though.

**Review by abstractj — DISMISSED** [review]
@stianst tested the new changes and they look good to me.

**Review by hmlnarik — COMMENTED** [review]
Late, but reviewed - it is excellent, thanks @stianst!

**Pull request merged**
