### PR TITLE
Update secure-jboss-app.adoc

### PR DESCRIPTION
**Pull request by zyv**
Fix unordered list formatting.

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
Thank you.

**Comment by stianst** [comment]
Looks correct to me already:
https://keycloak-docs.github.io/deploy-docs-pullrequest/PR/407/getting_started/index.html#securing-a-jboss-servlet-application

What's wrong here?

**Review by stianst — COMMENTED** [review]
See comment in conversation

**Comment by zyv** [comment]
@stianst it looks correct, because it *is* correct now.

The same error was apparently independently re-discovered several times later after I have submitted my PR (in #419 and #423) and PR #423 finally got merged without closing the two other duplicates.

I wish @matthewhelmke had immediately merged this PR directly after approving it, because leaving it open lead to several other people opening duplicate PRs and ensuing confusion. In the meantime, I think, this PR can be simply closed.

**Comment by matthewhelmke** [comment]
@zyv I apologize for the delay.

**Comment by zyv** [comment]
@matthewhelmke no problem & thanks for working on Keycloak; if the confusion is over, I'm just going to close this PR then.

**Pull request closed without merging**
