### PR TITLE
Updating Creating the first administrator chapter

### LINKED ISSUE #1482: Creating the first administrator chapter
### Description

Update this chapter in the Server Administration guide for the new Admin Console

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Minor changes for new admin console

Close #1482

### CODE REVIEW

**Comment by andymunro** [comment]
@ssilvert, @ikhomyn  Can you review this update.  Officially, it is part of the new Admin Console updates although the only changes needed were slight improvements in the content. Also I removed the reference to the installation guide, which is not part of Keycloak 19.

**Review by ikhomyn — DISMISSED** [review]
Hi @andymunro, Just verified it and looks correct.

**Comment by andymunro** [comment]
@ikhomyn @ssilvert I made two more minor change to rename and move a couple of files.  The SSO version now shows the Keycloak welcome screen because this documentation will not be used until SSO is renamed Keycloak.

**Comment by andymunro** [comment]
@ssilvert Can you review this PR and merge it if appropriate.   In this case, the changes are not specifically related to the new Admin Console, but there are few slight improvements to the content.

**Comment by ssilvert** [comment]
@andymunro I think you need to clean up this PR.  It has 22 commits from 15 different authors.

Is that last commit the only one that you intended to merge?  If so, create a PR with only that commit.  Let me know if you need help.

**Comment by andymunro** [comment]
Thanks, @ssilvert. I see the problem. I am closing this PR and opening a new one.

**Pull request closed without merging**
