### PR TITLE
Add possibility to provide path to keycloak.json

### PR DESCRIPTION
**Pull request by oldluke92**
Fulfilling https://issues.jboss.org/browse/KEYCLOAK-7341?_sscc=t

### CODE REVIEW

**Review by abstractj — CHANGES_REQUESTED** [review]
@oldluke92 thanks for submitting these changes. I would like suggest a different approach, something like:

```
The `Keycloak` class provides a central point for configuration
and integration with your application.  The simplest creation
involves no arguments.

[source,javascript]
----
    var session = require('express-session');
    var Keycloak = require('keycloak-connect');

    var memoryStore = new session.MemoryStore();
    var keycloak = new Keycloak({ store: memoryStore });
----

You may also provide the path to the JSON file (relative to the project directory).

[source,javascript]
----
    let keycloak = new Keycloak({ store: memoryStore }, './config/keycloak.json');
----

By default, this will locate a file named `keycloak.json` alongside
the main executable of your application to initialize keycloak-specific
settings (public key, realm name, various URLs).  The `keycloak.json` file
is obtained from the {project_name} Admin Console.
```
Does make sense for you?

**Comment by abstractj** [comment]
@oldluke92 would you like to move forward with this?

**Comment by oldluke92** [comment]
Sure.
I did not revisit this, as the change was that small I did not consider there would be a change request ...

**Comment by abstractj** [comment]
> Sure.
> I did not revisit this, as the change was that small I did not consider there would be a change request ...

Thank you!

**Comment by abstractj** [comment]
@oldluke92 It has been a while since we requested changes to this PR. While the submission is appreciated, we are not able to merge it without these changes. Because it has been so long, we are going to close the issue. Feel free to reopen with the changes included, if your time permits.

**Comment by oldluke92** [comment]
hi there.
I synced to the latest master and did the requested changes the exact day I last commented here ;)
Well .. here we go again.

**Comment by oldluke92** [comment]
okay. after syncing to the current master, rebasing my commit and pushing it to my repo, I found out that there is no way to "reopen" this for me. I would have to create a new PR.
This is not important enough to me, sorry.

**Pull request closed without merging**
