### PR TITLE
Add note on evaluated permissions when obtaining uma-ticket

### PR DESCRIPTION
**Pull request by sirkrypt0**
See https://github.com/keycloak/keycloak/issues/12512

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]
@sirkrypt0 Thanks, it will certainly help us and avoid replying the same answer :)

**Comment by pedroigor** [comment]
@sirkrypt0 Btw, do you mind changing the commit message to something like that:

```
Add note on evaluated permissions when obtaining uma-ticket

Closes #12512
```

**Comment by sirkrypt0** [comment]
> @sirkrypt0 Btw, do you mind changing the commit message to something like that:
> 
> ```
> Add note on evaluated permissions when obtaining uma-ticket
> 
> Closes #12512
> ```

Sure. I chose the link because the issue is in another repository but changed it to the issue number now :)

**Comment by pedroigor** [comment]
Thanks!

**Review by pedroigor — APPROVED** [review]

**Review by DGuhr — APPROVED** [review]

**Pull request merged**
