### PR TITLE
Convert Authorization Service to a flat topic structure

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
This update flattens the structure for the Authorization Services Guide so that it is easier to reorganize the content.

**Comment by sgilda** [comment]
It seems that the topics.adoc file is need to run the tests. We generally add the topics directly to the master.adoc file, but if you need them in topics.adoc, I can add the file back and move the updated topic includes to that file.

**Comment by sgilda** [comment]
Since is seems the topics.adoc file is included in the tests, I restored it and moved includes to it from master.adoc.

I'm not sure why this is showing the build warnings above. They do not appear in the asciidoctor or ccutil builds and the book renders correctly as far as I can tell.

**Comment by stianst** [comment]
PLEASE DO NOT MERGE

This approach is currently being discussed and changes should not be merged until we have reached a conclusion.

**Comment by sgilda** [comment]
Changes to files in authorization-services resulted in conficts in the authorization_services/topics/auth-services-terminology.adoc file. I fetched, rebased, and resolved the errors.

**Comment by stianst** [comment]
Opened a new PR to resolve merge conflicts and some issues:
https://github.com/keycloak/keycloak-documentation/pull/212

**Comment by stianst** [comment]
Closing in favour of https://github.com/keycloak/keycloak-documentation/pull/212

**Pull request closed without merging**
