### PR TITLE
[KEYCLOAK-11193] Add new `enableLogging` option to JS adapter

### PR DESCRIPTION
**Pull request by jonkoops**
See: https://github.com/keycloak/keycloak/pull/6270

### CODE REVIEW

**Comment by jonkoops** [comment]
Looks like the external link check is failing, but it seems unrelated to this PR.

**Review by mhajas — DISMISSED** [review]

**Review by mhajas — DISMISSED** [review]
Thank you @jonkoops. Looks good to me.

**Review by ssilvert — DISMISSED** [review]
Looks good.

**Comment by abstractj** [comment]
@stianst should we hold this?

**Comment by jonkoops** [comment]
@abstractj Yeah, let's I'll make some updates to it so it matches the new PR in: https://github.com/keycloak/keycloak/pull/6325

**Review by ssilvert — APPROVED** [review]

**Review by mhajas — APPROVED** [review]

**Review by abstractj — APPROVED** [review]

**Pull request merged**
