### PR TITLE
Merge ActionTokenStoreProvider and SingleUseObjectProvider

### LINKED ISSUE #13334: Merge ActionTokenStoreProvider and SingleUseObjectProvider
ActionTokenStoreProvider and SingleUseObjectProvider are currently separated and they should be merged into one as there is no strong reason to keep them separated.

### PR DESCRIPTION
**Pull request by martin-kanis**
Closes https://github.com/keycloak/keycloak/issues/13334

### CODE REVIEW

**Review by mhajas — APPROVED** [review]
Thanks @martin-kanis, LGTM

**Review by hmlnarik — CHANGES_REQUESTED** [review]
This needs to be announced in the Upgrading guide together with migration path.

**Comment by hmlnarik** [comment]
> This needs to be announced in the Upgrading guide together with migration path.

... as long as there needs to be any change in existing customization. Is there such a need? Please let me know.

**Comment by martin-kanis** [comment]
> > This needs to be announced in the Upgrading guide together with migration path.
> 
> ... as long as there needs to be any change in existing customization. Is there such a need? Please let me know.

Not sure if I understand. One title and one sentence mentioned `Action Token SPI` but the SPI is not actually touched by this section. It only touches `actionTokenHandler` SPI. Therefore I just renamed those occurrences and files and used "action token handler" which is subject of this section.

**Comment by hmlnarik** [comment]
> > > This needs to be announced in the Upgrading guide together with migration path.
> > 
> > 
> > ... as long as there needs to be any change in existing customization. Is there such a need? Please let me know.
> 
> Not sure if I understand. One title and one sentence mentioned `Action Token SPI` but the SPI is not actually touched by this section. It only touches `actionTokenHandler` SPI. Therefore I just renamed those occurrences and files and used "action token handler" which is subject of this section.

Thanks, that's what I got confused from. It looks well then

**Review by hmlnarik — APPROVED** [review]

**Review by andymunro — APPROVED** [review]

**Pull request merged**
