### PR TITLE
fix typo in configuration example of user storage provider

### PR DESCRIPTION
**Pull request by muehlburger**

### CODE REVIEW

**Comment by matthewhelmke** [comment]
@muehlburger Thank you!
@stianst Any idea why the build failed? Also, this looks to be a quick, small change to do a tech review, as time permits.

**Comment by stianst** [comment]
@matthewhelmke broken links - if you click on "Details" then go the logs in Travis you'll find out what link is broken. We need to send a separate PR to fix the link then restart this PR.

**Comment by stianst** [comment]
@matthewhelmke the change itself looks sound

**Comment by stianst** [comment]
Thanks

**Pull request merged**
