### PR TITLE
KEYCLOAK-9601 KEYCLOAK-9602 Jetty 8.1 and 9.1 removal

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/KEYCLOAK-9601
https://issues.jboss.org/browse/KEYCLOAK-9602

### CODE REVIEW

**Review by mhajas — CHANGES_REQUESTED** [review]
I found one more occurence of 9.1 adapter here: https://github.com/keycloak/keycloak-documentation/pull/634/files#diff-2d6b37bb5fbcb967fc69b25757415115R62 I am not sure whether it should be removed or changed to 9.x/2/3/4

**Review by mhajas — CHANGES_REQUESTED** [review]
I found one more occurence of 9.1 adapter here: https://github.com/keycloak/keycloak-documentation/pull/634/files#diff-2d6b37bb5fbcb967fc69b25757415115R62 I am not sure whether it should be removed or changed to 9.x/2/3/4

**Comment by slaskawi** [comment]
> I found one more occurence of 9.1 adapter here: https://github.com/keycloak/keycloak-documentation/pull/634/files#diff-2d6b37bb5fbcb967fc69b25757415115R62 I am not sure whether it should be removed or changed to 9.x/2/3/4

Thanks for spotting this @mhajas. This one should be fixed.

**Review by mhajas — APPROVED** [review]
@slaskawi Now it looks good to me.

**Review by vramik — APPROVED** [review]
@slaskawi LGTM thanks

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
