### PR TITLE
Note about default configuration

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by stianst** [comment]
@jenmalloy can you review and merge to 7.1 as well please?

**Comment by jenmalloy** [comment]
@pedroigor, Instead of "make sure to remove the *Default Resource*", change "make" to "be". That is, it should read: "be sure to remove the *Default Resource*..." Thanks!

**Comment by jenmalloy** [comment]
Closing PR since this was resolved with https://github.com/keycloak/keycloak-documentation/pull/35/files

**Comment by pedroigor** [comment]
@jenmalloy I was about to close this one :)

**Pull request closed without merging**
