### PR TITLE
KEYCLOAK-16923-FIX Revising Authorization Services Guide for Red Hat Standards

### PR DESCRIPTION
**Pull request by andymunro**

### CODE REVIEW

**Comment by andymunro** [comment]
@pskopek I duplicated this PR: https://github.com/keycloak/keycloak-documentation/pull/1218 and fixed the Context error.  Now instead external link failures are showing up.  However, these links are working.  

For example, the report is that it cannot reach: https://datatracker.ietf.org/doc/html/rfc7519

This link to the "Oauth Specification" already works.  It is in the built version of the Securing Apps Guide on keycloak.org;  https://www.keycloak.org/docs/latest/securing_apps/index.html#other-openid-connect-libraries

This was already approved by QE for the original PR.

**Comment by andymunro** [comment]
fwojnar@redhat.com,  you approved this in downstream. https://gitlab.cee.redhat.com/keycloak/keycloak-documentation-prod/-/merge_requests/66  We need to reflect these changes in upstream. Can you review and approve again?
@drichtarik Can you also review this PR for upstream.

**Review by wojnarfilip — DISMISSED** [review]

**Comment by andymunro** [comment]
@wojnarfilip Is this okay now to be approved?

**Comment by andymunro** [comment]
Thanks, @wojnarfilip 
@drichtarik Can you approve this also. It's already approved in downstream.  We need to keep upstream current.

**Comment by andymunro** [comment]
@abstractj  Can you approve this upstream PR, which Filip has approved for QE. It is actually been around since December and I would like to close it thiis quarter.

**Comment by abstractj** [comment]
@andymunro I understand that. But let's allow people to review, and approve, prior to merge.

**Comment by andymunro** [comment]
Okay, thanks, @abstractj

**Review by wojnarfilip — APPROVED** [review]
LGTM. Looks good

**Comment by andymunro** [comment]
Thanks, @wojnarfilip.  We just need development approval now so it can be merged.

**Comment by andymunro** [comment]
@pskopek Can you review this? The only errors are for when the build script cannot find the product guides and this is for upstream.

**Review by pedroigor — APPROVED** [review]

**Comment by andymunro** [comment]
Thank you, @pedroigor.  Since it also approved by QE, can you merge this?

**Review by abstractj — APPROVED** [review]

**Comment by andymunro** [comment]
Thanks, @abstractj, @pedroigor

**Pull request merged**
