### PR TITLE
KEYCLOAK-18360 Update release notes about deprecated RPMS

### PR DESCRIPTION
**Pull request by andymunro**
@sguilhen Can you verify this note?   This was originally part of a different PR. https://github.com/keycloak/keycloak-documentation/pull/1176/

### CODE REVIEW

**Review by sguilhen — DISMISSED** [review]
I think this is ok.

**Comment by sguilhen** [comment]
@andymunro What's up with the prod build that is complaining about missing images?

**Comment by andymunro** [comment]
If you mean the broken links that break every PR, @pskopek said the build script is the problem.  Is that correct, @pskopek ?

**Comment by sguilhen** [comment]
No, not the broken links. If you check the failed tests (hit Details link next to it) you will see that it is complaining about missing images

**Comment by andymunro** [comment]
@sguilhen I only found a reference to one missing file: client-oidc-keys.png

I added it.

**Comment by sguilhen** [comment]
@andymunro It seems that it fixed the build errors, thanks!

**Review by sguilhen — APPROVED** [review]

**Review by pedroigor — APPROVED** [review]

**Comment by andymunro** [comment]
Great! Who can I ask to approve and merge this?

**Pull request merged**
