### PR TITLE
KEYCLOAK-16774 Incorrect info about account2 and account_api profiles in Server Installation Guide

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Review by ssilvert — DISMISSED** [review]

**Comment by ssilvert** [comment]
@vmuzikar I've approved that change but I don't know what we should do about the build.  I'm not allowed to merge it with failures.

**Comment by vmuzikar** [comment]
@ssilvert Thanks for the review. The test errors were unrelated to this change (broken links) and were apparently fixed by [KEYCLOAK-16788](https://issues.redhat.com/browse/KEYCLOAK-16788). I rebased this and also fixed one new link error.

**Comment by vmuzikar** [comment]
The tests failed again but only for RH-SSO. Since it is really out of scope of this PR, I created [KEYCLOAK-16990](https://issues.redhat.com/browse/KEYCLOAK-16990) and suggest to merge this.

**Review by ssilvert — APPROVED** [review]

**Comment by ssilvert** [comment]
> The tests failed again but only for RH-SSO. Since it is really out of scope of this PR, I created [KEYCLOAK-16990](https://issues.redhat.com/browse/KEYCLOAK-16990) and suggest to merge this.

I agree but I believe it will take an admin to do the merge.  It won't let me do it.

**Review by abstractj — APPROVED** [review]

**Pull request merged**
