### PR TITLE
Keycloak 16916 Document Account Console

### PR DESCRIPTION
**Pull request by andymunro**
@ssilvert How does this look?

### CODE REVIEW

**Review by ssilvert — CHANGES_REQUESTED** [review]
This doesn't mention or cover Webauthn or Webauthn passwordless as additional signin options.  You might need to talk to Marek for details.

**Comment by andymunro** [comment]
@mposolda Would you be able to contribute something on Webauthn or Webauthn passwordless as additional signin options? I am not certain we have anything in the existing Server Administration guide.

**Comment by mposolda** [comment]
@andymunro Hi, I am not sure about the time until the end of May due the client policies feature, which is biggest priority for me. However after RHSSO 7.5 code-freeze, I can help.

**Comment by andymunro** [comment]
Thanks for the quick response, @mposolda.  Yes I agree that is the priority. I need to focus now on fixing documentation bugs for the rest of the month.

**Comment by andymunro** [comment]
@mposolda Would you have time to give input on Webauthn or Webauthn passwordless as additional signin options now for RH SSO 7.5?

**Comment by andymunro** [comment]
@pedroigor @ssilvert.  I have integrated Marek's input on WebAuthn for the Account Console. Is this ready to be approved and merged?

**Comment by andymunro** [comment]
@abstractj Would you be able to review this PR?

**Review by mposolda — APPROVED** [review]

**Pull request merged**
