### PR TITLE
KEYCLOAK-15079 Resolve four test failures

### PR DESCRIPTION
**Pull request by ASzc**
This PR resolves these test failures, currently on master:

```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 38.833 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.SecuringAppsTest)  Time elapsed: 38.723 sec  <<< FAILURE!
* http://undertow.io/ (invalid redirect to https://undertow.io/)

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.999 sec <<< FAILURE!
checkVariables(org.keycloak.documentation.test.GettingStartedTest)  Time elapsed: 0.004 sec  <<< FAILURE!
* context

Running org.keycloak.documentation.test.ServerInstallationTest
```

And these product test failures:

```
Running org.keycloak.documentation.test.GettingStartedTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.79 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.GettingStartedTest)  Time elapsed: 0.767 sec  <<< FAILURE!
* http://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/ (invalid redirect to https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/)

Running org.keycloak.documentation.test.OpenShiftTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.502 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.OpenShiftTest)  Time elapsed: 8.404 sec  <<< FAILURE!
* https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/html-single/red_hat_single_sign-on_for_openshift_on_openj9/ (invalid status code 404)
```

### CODE REVIEW

**Comment by ASzc** [comment]
All tests pass now, so this PR is good to go

**Review by iankko — DISMISSED** [review]
/lgtm

**Comment by ASzc** [comment]
Ported over the context fix from #1012, hopefully I've done it correctly. If the tests pass, then this PR should be good to merge

**Comment by iankko** [comment]
> Ported over the context fix from #1012, hopefully I've done it correctly. If the tests pass, then this PR should be good to merge

Yeah, it was just about the defining the `:context:` attribute as empty string in `getting_started/index.adoc` (since it already was present in `getting_started/master.adoc`) IIRC.

**Review by iankko — APPROVED** [review]

**Comment by iankko** [comment]
@andymunro @abstractj PTAL once got a chance

**Comment by andymunro** [comment]
@abstractj Can you merge this so we can backport it to PROD?

**Review by abstractj — APPROVED** [review]

**Pull request merged**
