### PR TITLE
KEYCLOAK-6800 added instructions for deleting users

### PR DESCRIPTION
**Pull request by matthewhelmke**
This new section parallels the phrasing and construction of the adding users section, so it should be pretty quick to review.

### CODE REVIEW

**Comment by stianst** [comment]
Changes looks good to me, but there's some screw up with regards to commits. @matthewhelmke can you sort that out so there's only the single commit for adding delete user instructions?

**Comment by stianst** [comment]
FIY https://github.com/keycloak/keycloak-documentation/pull/357 should fix the broken test

**Review by stianst — CHANGES_REQUESTED** [review]
Fix commits

**Comment by matthewhelmke** [comment]
Sorted

**Review by stianst — APPROVED** [review]

**Pull request merged**
