### PR TITLE
KEYCLOAK-13958 Document updating and regenerating a client secret with kcadm.sh

### PR DESCRIPTION
**Pull request by thomasdarimont**

### CODE REVIEW

**Comment by thomasdarimont** [comment]
@mposolda can you review this?

**Comment by thomasdarimont** [comment]
I think the build errors are unrelated to this change
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.keycloak.documentation.test.SecuringAppsTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.184 sec
Running org.keycloak.documentation.test.AuthorizationServicesTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.577 sec
Running org.keycloak.documentation.test.GettingStartedTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.138 sec
Running org.keycloak.documentation.test.ServerDeveloperTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.594 sec
Running org.keycloak.documentation.test.ReleaseNotesTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 22.205 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.ReleaseNotesTest)  Time elapsed: 22.165 sec  <<< FAILURE!
* https://www.owasp.org/index.php/SameSite (invalid status code 404)

Running org.keycloak.documentation.test.ServerAdminTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.345 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.ServerAdminTest)  Time elapsed: 25.181 sec  <<< FAILURE!
* https://docs.jboss.org/author/display/WFLY10/Admin+Guide#AdminGuide-EnableSSL (invalid anchor AdminGuide-EnableSSL)
* https://docs.jboss.org/author/display/WFLY10/Admin+Guide#AdminGuide-%7B%7B%3Cssl%2F%3E%7D%7D (invalid anchor AdminGuide-%7B%7B%3Cssl%2F%3E%7D%7D)
* https://docs.jboss.org/author/display/WFLY10/Admin+Guide#AdminGuide-HTTPSlistener (invalid anchor AdminGuide-HTTPSlistener)
* https://mirocupak.com/logging-requests-with-undertow/ (invalid status code 404)

Running org.keycloak.documentation.test.OpenShiftTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.043 sec
Running org.keycloak.documentation.test.ServerInstallationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.116 sec
Running org.keycloak.documentation.test.UpgradingTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.394 sec

Results :

Failed tests:   checkExternalLinks(org.keycloak.documentation.test.ReleaseNotesTest): Invalid links
  checkExternalLinks(org.keycloak.documentation.test.ServerAdminTest): Invalid links
```

**Comment by thomasdarimont** [comment]
@mposolda would you mind taking a look at this? :)

**Review by mposolda — APPROVED** [review]
@thomasdarimont Thanks! I am adding @andymunro as reviewer as well.

**Review by andymunro — APPROVED** [review]

**Comment by mposolda** [comment]
@andymunro Thanks for the review!

**Pull request merged**
