### PR TITLE
KEYCLOAK-15379: [Findability Prerequisite] added a :context: attribute to the master.…

### PR DESCRIPTION
**Pull request by inoxx03**
…adoc of the Server Installation and Configuration Guide.

@pskopek and @andymunro Please let me know if the formatting of the attribute value is OK, or if there are any changes that I should make in addition to those found in this PR. 

Thank you

### CODE REVIEW

**Review by andymunro — COMMENTED** [review]
Thanks, @inoxx03 
The same change needs to be made to index.adoc.
So now you get to test the instructions I wrote for updating a PR.

Also, can you include the JIRA in the comment line?

**Comment by andymunro** [comment]
@inoxx03 Also, after you update index.adoc, can you test using the Maven instructions that the Keycloak version works?

**Comment by andymunro** [comment]
@inoxx03 Also, Please use the convention "KEYCLOAK-JIRA number  xxxx" in the message as in the instructions.

**Comment by inoxx03** [comment]
@andymunro @pskopek Thank you for the initial review and feedback. I have updated this PR according to your suggestions:
* I added `:context:` to `index.adoc` as well as to `master.adoc`
* I have filed a [JIRA](https://issues.redhat.com/browse/KEYCLOAK-15379) and referenced it in the individual commit messages and the PR name (I have deliberately refrained from renaming the source branch on a live PR, because it might, as far as my experience goes, break the PR. Sorry about that.)
* Have tested both product and community builds locally using the standard tools (CCUTIL for product and Maven for community). Both builds succeeded locally , although there seems to be an exception that causes the community Travis CI tests to fail. The cause of said failure seems to be an invalid external link in the Getting Started Guide, as evidenced by:

```
Failed tests:   checkExternalLinks(org.keycloak.documentation.test.GettingStartedTest): Invalid links
  checkExternalLinks(org.keycloak.documentation.test.SecuringAppsTest): Invalid links
```

Therefore, it seems unlikely that the edits I made in this PR are causing this failure.
@pskopek is this a  known issue?

Please let me know, whether I should make any additional changes. Thank you:)

**Comment by inoxx03** [comment]
@pskopek @andymunro Apologies, this seems to have been the incorrect fork to file this PR against. Sorry about the trouble. I'm closing this PR as invalid. Please feel free to disregard any and all of my unanswered questions above.

**Pull request closed without merging**
