### PR TITLE
KEYCLOAK-FIX Reinstating missing content.

### PR DESCRIPTION
**Pull request by andymunro**
@pskopek @iankko I have added the OCP 4.x procedure related to this Jira: https://issues.redhat.com/browse/KEYCLOAK-13553 This would be good to include in 7.4.2.

### CODE REVIEW

**Comment by andymunro** [comment]
@lhanusov.  Can you verify that I have added what @iankko suggests?

**Review by lhanusov — APPROVED** [review]
@andymunro I am fine with it, because Jano already asked me to review it few months ago. Anyway I checked it again and I agree that it can be merged.

**Comment by andymunro** [comment]
Thanks, @lhanusov.  I think this one had a merge conflict, which is why it had to be double-checked.  Thanks for confirming.

**Comment by iankko** [comment]
> @pskopek @iankko I have added the OCP 4.x procedure related to this Jira: https://issues.redhat.com/browse/KEYCLOAK-13553 This would be good to include in 7.4.2.

@andymunro Thank you for the change, Andy! But wondering, what's the expected way / form on how the newly added procedure should be rendered? This is, how it renders right now:

deploying_ocp4_template_procedure

But instead of the current form, expecting those newly added numbered steps should be clickable links (taking e.g. `3. Click From Catalog.` as an example), and there shouldn't be specific image name listed below each of the steps, is that correct?

**Comment by iankko** [comment]
@andymunro Sorry, my bad, used wrong tool to render the content. Ignore my previous comment (deleted it).

**Comment by iankko** [comment]
@andymunro LGTM. But could you adjust the commit message, so it mentions it's fixing the KEYCLOAK-13553 issue?

You can do this as follows:

Having your ```master``` branch with the change cloned locally:
```
[iankko@localhost keycloak-documentation]$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:andymunro/keycloak-documentation.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
With the latest commit current message as follows:

```
[iankko@localhost keycloak-documentation]$ git log -n 1
commit 4038881383abdb516dca8b5775aba408ee1a93f3 (HEAD -> master, origin/master, origin/HEAD)
Author: Lorent Lempereur <looorent@users.noreply.github.com>
Date:   Fri Jul 24 21:42:12 2020 +0200

    KEYCLOAK-FIX Reinstating missing content.
```
you can reset / modify it by issuing:

```
$ git commit --amend -s
```

And enter the following into the CLI editor, that gets opened:
```
    [KEYCLOAK-13553] Reinstating missing content.
    
    Signed-off-by: Andrew Munro <amunro@redhat.com>
```

And save the change (```:wq```)

The result will then look as follows:
```
$ git log -n 1
commit e5593e1cec0e04069380fe9f1f2856ed98478336 (HEAD -> master)
Author: Lorent Lempereur <looorent@users.noreply.github.com>
Date:   Fri Jul 24 21:42:12 2020 +0200

    [KEYCLOAK-13553] Reinstating missing content.
    
    Signed-off-by: Andrew Munro <amunro@redhat.com>
```

HTH, Jan

**Review by iankko — APPROVED** [review]
LGTM

Would be great to have the commit message to reference / mention it's fixing KEYCLOAK-13553 actually. But the content / code change itself looks OK (including the pictures)

**Comment by andymunro** [comment]
Thanks again, @iankko.  That helps a lot.

**Comment by andymunro** [comment]
@abstractj This is approved, so it's ready to be merged.

**Pull request merged**
