### PR TITLE
KEYCLOAK-18497 - UserProfile - support different input types in built-in dynamic forms

### PR DESCRIPTION
**Pull request by velias**
https://github.com/keycloak/keycloak/pull/8370

### CODE REVIEW

**Review by pedroigor — DISMISSED** [review]
@andymunro PR merged in upstream, could you please see what else is missing to get tests passing and merge?

**Comment by andymunro** [comment]
I had a separate MR that reported problems with links and invalid redirects and spent several days working on those links.

I think I fixed all of them.  For this PR, I see 3 invalid redirects, but all of them actually go to the correct place.  However, I did replace the redirected URL with the official URL where I could

**Comment by andymunro** [comment]
@pedroigor When I build the other PR, it only shows invalid redirects to a 7.5 site that is not live yet:  https://github.com/keycloak/keycloak-documentation/runs/3656115945?check_suite_focus=true

**Comment by pedroigor** [comment]
Thanks, @andymunro. So I guess there is nothing else @velias can do?

**Comment by andymunro** [comment]
Yes, no need for any more changes.  I will backport my PR to PROD for 7.5 once my PR is approved.

Is your PR going into 7.5 or a 7.4.10?  If it is 7.4.10, are you backporting it to PROD?

**Comment by pedroigor** [comment]
This is upstream work, it is not going to prod AFAIK.

**Comment by andymunro** [comment]
Thanks, @pedroigor.  That works.

**Comment by velias** [comment]
Rebased to latest master with changed levels of headings

**Pull request merged**
