### PR TITLE
first pass at editing Sections 19.1 through 19.6

### PR DESCRIPTION
**Pull request by leswilliams44**
Matthew:

Here is my first pass at editing the Admin CLI topic. I stopped at Section 19.6 so you could see if I was on the right track. If I am not editing it as you'd like me to, let's set up a BlueJeans meeting so I can better understand what you are looking for.

Les

### CODE REVIEW

**Comment by matthewhelmke** [comment]
This is exactly what I am looking for. Please continue.

**Comment by leswilliams44** [comment]
I am closing this request so I can continue working in the same branch.

**Comment by leswilliams44** [comment]
Closed the request so I can work in the same branch. Please let me know if this is not acceptable behavior.

**Comment by matthewhelmke** [comment]
You don't need to close the PR. Just keep working in the same branch and when you commit/push, this PR will be updated.

**Comment by matthewhelmke** [comment]
@leswilliams44, I did some checking and this project prefers to have all the changes in one commit. That is different from how I have worked in the past (but not wrong, just different). So, I think your first hunch was the correct one. I'm going to close this and when you have all the changes ready, please open a new PR.

**Comment by leswilliams44** [comment]
Will do, Matthew. I should be through with this file by tomorrow at the latest.

**Pull request closed without merging**
