### PR TITLE
Add missing parantheses

### PR DESCRIPTION
**Pull request by anton-johansson**

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
Thank you! Your attention to detail is appreciated.

**Comment by anton-johansson** [comment]
No worries. Just stumbled over it while reading the documentation and I got a bit confused. :)

**Comment by matthewhelmke** [comment]
Please feel free to do so anytime you see an issue! The extra eyes and assistance are always appreciated. :)

**Comment by anton-johansson** [comment]
You can expect nothing less!

**Pull request merged**
