### PR TITLE
[KEYCLOAK-14970] Fix various invalid links / invalid redirects in GettingStartedTest and OpenShiftTest tests

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-14970] Fix various invalid links / invalid redirects in
    GettingStartedTest and OpenShiftTest tests
    
    Example failure: https://travis-ci.com/github/keycloak/keycloak-documentation/jobs/366838002
    
    While at this, also fix the missing "context" variable, when
    running the documentation tests on the "community" profile. Example
    failure in:
      https://travis-ci.com/github/keycloak/keycloak-documentation/jobs/371303907
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Further background: As demonstrated by [a recent job](https://travis-ci.com/github/keycloak/keycloak-documentation/jobs/366838002) running the documentation checks on the product:

```
export PROFILE=product
```

```
mvn clean install -DskipTests -B -q -D$PROFILE
```

```
mvn test -f tests/pom.xml -D$PROFILE -B -fae
```

fails with the current documentation repository `master` as follows:
```
$  mvn test -f tests/pom.xml -D$PROFILE -B -fae
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.keycloak.documentation:tests >------------------
[INFO] Building Tests 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/test/keycloak-documentation/tests/src/main/resources
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:copy-resources (asciidoc-copy-resources) @ tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ tests ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ tests ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tests ---
[INFO] Surefire report directory: /tmp/test/keycloak-documentation/tests/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.keycloak.documentation.test.AuthorizationServicesTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.141 sec
Running org.keycloak.documentation.test.ServerInstallationTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.883 sec
Running org.keycloak.documentation.test.GettingStartedTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.839 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.GettingStartedTest)  Time elapsed: 0.827 sec  <<< FAILURE!
* http://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/ (invalid redirect to https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/)

Running org.keycloak.documentation.test.ReleaseNotesTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.725 sec
Running org.keycloak.documentation.test.UpgradingTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.602 sec
Running org.keycloak.documentation.test.SecuringAppsTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 40.389 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.SecuringAppsTest)  Time elapsed: 40.232 sec  <<< FAILURE!
* http://undertow.io/ (invalid redirect to https://undertow.io/)

Running org.keycloak.documentation.test.ServerAdminTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 54.704 sec
Running org.keycloak.documentation.test.OpenShiftTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.179 sec <<< FAILURE!
checkExternalLinks(org.keycloak.documentation.test.OpenShiftTest)  Time elapsed: 20.114 sec  <<< FAILURE!
* https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1/html-single/red_hat_single_sign-on_for_openshift_on_openj9/ (invalid status code 404)

Running org.keycloak.documentation.test.ServerDeveloperTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.376 sec

Results :

Failed tests:   checkExternalLinks(org.keycloak.documentation.test.GettingStartedTest): Invalid links
  checkExternalLinks(org.keycloak.documentation.test.SecuringAppsTest): Invalid links
  checkExternalLinks(org.keycloak.documentation.test.OpenShiftTest): Invalid links

Tests run: 45, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2020-08-12T17:19:33+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /tmp/test/keycloak-documentation/tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

This change should fix those failing tests.

### CODE REVIEW

**Comment by iankko** [comment]
@andymunro @pskopek @abstractj @mposolda @stianst PTAL once got a chance

Thanks!
Jan

**Comment by iankko** [comment]
While was at this, updated the PR to fix also the missing `context` variable when running the tests on the `community` profile. Example failure is here: https://travis-ci.com/github/keycloak/keycloak-documentation/jobs/371303907

Docs tests for both profiles should be passing now.

**Review by andymunro — APPROVED** [review]
Thanks, Jan for making these important corrections.

**Comment by ASzc** [comment]
Duplicates #1010 . I think this has a better solution as far as `context` goes. I think my solution for the broken URLs is better, as I'm pretty sure `project_versionDoc` should not have been changed to the value of `7.4.1`, it should have stayed on `7.4`.

**Comment by iankko** [comment]
> Duplicates #1010 . 

Ouch, didn't know, there's a duplicate PR & associated JIRA (noticed the test failures when dealing with KEYCLOAK-13280 & promised to fix them).

> I think this has a better solution as far as `context` goes. 
> I think my solution for the broken URLs is better, as I'm pretty sure `project_versionDoc` should not have been changed to the value of `7.4.1`, it should have stayed on `7.4`.

Right, was thinking about the way how to fix it. Using `blame` noticed the `:versionDoc:` got bumped from `7.4` to `7.4.1` via [PR for KEYCLOAK-14658](https://github.com/keycloak/keycloak-documentation/pull/973). Though looking at the [changes in that PR](https://github.com/keycloak/keycloak-documentation/pull/973/files) doesn't seem the updated value of `versionDoc` is actually needed for some reference / URL (IOW looks it was just accidental change). So maybe it's OK to revert the `versionDoc` value change from `7.4.1` back to `7.4` (the `7.4.1` is what's actually causing the failures, since the documentation doesn't have micro version in the URL, just the `major.minor` combination, e.g.:

 `https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/`

is valid link, while:

  `https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4.1`

is invalid one (HTTP 404 Not Found).

@andymunro Can you clarify, if you need the `versionDoc` value to be set to `7.4.1` due some reason (since per KEYCLOAK-14658 change above it got updated only by accident), and if we can cut it down back to the `7.4` original value? (since this would solve the invalid links problem in the tests too)

@ASzc I am OK with fixing this test failures either way. If @andymunro is OK with lowering `versionDoc` back to original `7.4` value, I am OK with that too.

Thanks, Jan

**Comment by andymunro** [comment]
Thanks, @iankko and @ASzc for find this and making the suggestions.  Yes, please revert versionDoc to 7.4.

**Comment by iankko** [comment]
> Thanks, @iankko and @ASzc for find this and making the suggestions. Yes, please revert versionDoc to 7.4.

@andymunro Ok, great, thanks! @ASzc I am going to close this one as dupe of your's one since you have "lowering" of `versionDoc` to `7.4` already. Feel free to reuse the `context` approach, if you want.

**Comment by iankko** [comment]
Dupe of https://github.com/keycloak/keycloak-documentation/pull/1010, closing

**Comment by ASzc** [comment]
I'll update mine to use your solution for `context`

**Comment by andymunro** [comment]
@pskopek @sguilhen This is necessary to be approved so it can be cherry-picked for 7.4.2.  @abstractj Can you merge this?

**Comment by sguilhen** [comment]
Why are we reviewing this PR when it was closed because it duplicates #1010?

**Comment by andymunro** [comment]
Thanks, you are right. https://github.com/keycloak/keycloak-documentation/pull/1010 replace this one.

**Pull request closed without merging**
