### PR TITLE
Update migration guide and release notes for ubi9-micro

### PR DESCRIPTION
**Pull request by ASzc**

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]
@ASzc Thanks, LGTM! We kinda missed this in 21 release notes.

I think we also need a review from @stianst.

**Comment by vmuzikar** [comment]
This depends on backporting of https://github.com/keycloak/keycloak/pull/17317

**Comment by ahus1** [comment]
@vmuzikar / @ASzc - as you know we're trying to wrap up the open PRs in this repo over the next days.
This PR refers to an issue in the main repository that has been merged to main. While this PR states that it should be backported, it also targets main and therefore I assume it can be merged as well. 
To backport it to the existing KC21 docs, consider creating a PR against the release branch after this PR has been merged.
Thanks!

**Comment by vmuzikar** [comment]
@ahus1 Thanks for the heads-up! If we merge it to `main` now, doesn't it mean it'll be published right away?

> To backport it to the existing KC21 docs, consider creating a PR against the release branch after this PR has been merged.

Do you mean release branch in `keycloak/keycloak` repo?

**Comment by ahus1** [comment]
> If we merge it to main now, doesn't it mean it'll be published right away?

No, it will be published as part of the next docs release (KC22). 

> Do you mean release branch in `keycloak/keycloak` repo

No, there is a release branch in `keycloak/keycloak-documentation` as well, which is for the docs.

**Pull request merged**
