### PR TITLE
KEYCLOAK-16922 Revising Server Development Guide per Red Hat standards

### PR DESCRIPTION
**Pull request by andymunro**
@pdrozd Here is one more guide for you review when you have a chance.

### CODE REVIEW

**Comment by andymunro** [comment]
ikhomyn@redhat.com  
This is rebased now, so it's okay to check it.  I think the error in the Keycloak version refers to a build script error.

**Comment by andymunro** [comment]
@ikhomyn Any more input on this guide?

**Review by pdrozd — DISMISSED** [review]
Approve based on Ivan's review

**Comment by andymunro** [comment]
Thanks, @ikhomyn, @pdrozd.

**Comment by andymunro** [comment]
@hmlnarik  Would you be able to review this PR?  It is already approved by QE.

**Review by stianst — APPROVED** [review]

**Pull request merged**
