### PR TITLE
Updated configuring realms chapter - issue 1483 (new)

### PR DESCRIPTION
**Pull request by agagancarczyk**
Duplicate of https://github.com/keycloak/keycloak-documentation/pull/1533 but different recipient branch.

### CODE REVIEW

**Comment by andymunro** [comment]
@agagancarczyk It looks like there are multiple commits, not just one commit.

**Comment by agagancarczyk** [comment]
This is the result of rebasing. Are the other commits wrong? @ssilvert this is ok, right?

**Comment by andymunro** [comment]
I am not certain @agagancarczyk because I see this includes commits from Alexander and Marek which went to main. @ssilvert would know best.

**Comment by ssilvert** [comment]
@agagancarczyk I think something went wrong when you tried to rebase.  I think it would all work out ok, but it's best if you clean this up before we try to review.  The PR shows 62 files changed.

Just take a fresh updated version of the new-admin-console branch.  Then cherry-pick your commit on top of it and do a PR from that.  Then your PR should look clean.

**Comment by agagancarczyk** [comment]
> @agagancarczyk I think something went wrong when you tried to rebase. I think it would all work out ok, but it's best if you clean this up before we try to review. The PR shows 62 files changed.
> 
> Just take a fresh updated version of the new-admin-console branch. Then cherry-pick your commit on top of it and do a PR from that. Then your PR should look clean.

Thanks @ssilvert ! @andymunro I have created a new branch https://github.com/keycloak/keycloak-documentation/pull/1558 with only my changes. Hope this is ok now. Thanks

**Comment by agagancarczyk** [comment]
This can now be closed.

**Pull request closed without merging**
