### PR TITLE
Update multi-tenancy.adoc

### PR DESCRIPTION
**Pull request by bender316**
Provide proper Java for KeycloakConfigResolver example

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
Thank you. This looks good to me. We always have two reviews: one by me from a technical writing standpoint and a second by engineering to confirm the details are accurate. You have passed my review.

**Comment by abstractj** [comment]
@bender316 @matthewhelmke I believe we need a Jira for this, but meanwhile let me add some comments.

**Comment by abstractj** [comment]
@bender316 why not just a minor update of this, like:

```
import org.keycloak.adapters.KeycloakConfigResolver;
import org.keycloak.adapters.KeycloakDeployment;
import org.keycloak.adapters.KeycloakDeploymentBuilder;
import org.keycloak.adapters.OIDCHttpFacade;

import java.io.InputStream;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class PathBasedKeycloakConfigResolver1 implements KeycloakConfigResolver {

    private final Map<String, KeycloakDeployment> cache = new ConcurrentHashMap<String, KeycloakDeployment>();
    
    @Override
    public KeycloakDeployment resolve(OIDCHttpFacade.Request request) {
        String path = request.getRelativePath();
        String realm = "realm";
        if (path.startsWith("alternative")) {
            KeycloakDeployment deployment = cache.get(realm);
            if (null == deployment) {
                InputStream is = getClass().getResourceAsStream("/tenant1-keycloak.json");
                return KeycloakDeploymentBuilder.build(is);
            }
        } else {
            InputStream is = getClass().getResourceAsStream("/default-keycloak.json");
            return KeycloakDeploymentBuilder.build(is);
        }
        return null;
    }

}
```

The docs are based on this example: https://github.com/keycloak/keycloak/blob/master/examples/multi-tenant/src/main/java/org/keycloak/example/multitenant/control/PathBasedKeycloakConfigResolver.java. So I believe we need to update that too.

**Review by abstractj — CHANGES_REQUESTED** [review]
Please, see the comments.

**Comment by stianst** [comment]
Closing due to lack of feedback

**Pull request closed without merging**
