### PR TITLE
OpenShift Guide: Updating template reference

### PR DESCRIPTION
**Pull request by andymunro**
Closes #CIAM-2517

### CODE REVIEW

**Comment by andymunro** [comment]
pzaoral@redhat.com and @drichtarik please review and merge. Then I will create the MR to backport this downstream for SSO 7.5.2

**Review by Pepo48 — APPROVED** [review]
LGTM, thanks @andymunro!

**Comment by andymunro** [comment]
@drichtarik Can you approve this so someone can merge it?

**Comment by andymunro** [comment]
@hmlnarik would you be able to approve this. It's a minor correction.

**Review by iankko — APPROVED** [review]
LGTM @andymunro Thanks, Andy!

**Comment by iankko** [comment]
@pskopek @sguilhen Could you possibly merge this? (should be a no-brainer / simple, expected change)

Thanks!
Jan

**Comment by andymunro** [comment]
Thanks, @iankko 
@abstractj This is approved by QE and development.  Can you merge this PR which is needed for 7.5.2?

**Comment by andymunro** [comment]
Thanks, @abstractj

**Pull request merged**
