### PR TITLE
Updated account console chapter #1494

### PR DESCRIPTION
**Pull request by agagancarczyk**
This PR is for https://github.com/keycloak/keycloak-documentation/issues/1494.

Updated all sections and screenshots except for:
==== Two-factor authentication with WebAuthn 
==== Passwordless authentication with WebAuthn

### CODE REVIEW

**Review by andymunro — CHANGES_REQUESTED** [review]
Looks great, @agagancarczyk. But is there any way to reduce the size of the screens before capturing them? It would be great if the screens lunch could be smaller and the text on the screens is closer to the size of the text in the instructions.  
If you cannot resize them before capturing them, I might be able to use GIMP to shrink them.

**Comment by agagancarczyk** [comment]
> Looks great, @agagancarczyk. But is there any way to reduce the size of the screens before capturing them? It would be great if the screens lunch could be smaller and the text on the screens is closer to the size of the text in the instructions. If you cannot resize them before capturing them, I might be able to use GIMP to shrink them.

hi @andymunro I have resized all new screenshots. Hope they look good now.

**Review by andymunro — CHANGES_REQUESTED** [review]
Thanks, @agagancarczyk. Looks great. However, needs to be merged to upstream/new-admin-console.

**Review by andymunro — APPROVED** [review]
Actually, on second thought, this PR is not really related to the new Admin Console, so why don't we just merge this to main. 
Okay to merge @ssilvert

**Review by ssilvert — APPROVED** [review]

**Comment by edewit** [comment]
@ssilvert this one also went into main instead of `new-admin-console`

**Comment by andymunro** [comment]
Yes, thanks, @edewit.  @ssilvert and I decided it's okay, because it is actually a valid update independent of the new Admin Console.

**Pull request merged**
