### PR TITLE
Preparing Securing Apps and Authorization Services Guides for RHBK

### LINKED ISSUE #1682: Prepare Securing Apps and Authorization Services Guide for RHBK
### Description

We need to remove all the conditionally coded content for the old Admin Console in preparation for a release of Red Hat Build of Keycloak that features the new Admin Console.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by andymunro**
Closes #1682

### CODE REVIEW

**Comment by andymunro** [comment]
Removing coding to conditionally include old Admin Console, moving all Keycloak-images files to the images directory, and deleting the rhsso-images directory.

**Comment by andymunro** [comment]
I have checked the failure reports and they are a result of an inadequate build script.  Everything works.

**Review by Aboullos — DISMISSED** [review]
LGTM!

**Review by ssilvert — DISMISSED** [review]

**Comment by andymunro** [comment]
@ssilvert I have checked the failure reports and they are a result of an inadequate build script. Everything works.

**Comment by andymunro** [comment]
@ssilvert Now this one is no longer failing any test. Ready to merge.

**Review by ssilvert — DISMISSED** [review]

**Review by ssilvert — APPROVED** [review]

**Pull request merged**
