### PR TITLE
Update tar commad

### PR DESCRIPTION
**Pull request by rabajaj0509**

### CODE REVIEW

**Comment by abstractj** [comment]
@rahulbajaj0509 could you please elaborate about this change?

`tar -xzvf` and `tar xzvf` have the same effects for me.

**Review by abstractj — COMMENTED** [review]
See the comments above.

**Comment by rabajaj0509** [comment]
I checked the man page, using a hyphen is standard practice, therefore I am closing the pull request. Thanks @abstractj

**Comment by abstractj** [comment]
@rahulbajaj0509 thanks for submitting this change. For now I'm closing this PR, because there's no reason to change it, as the command works as expected. 

Feel free to submit more changes if you find any issues at your docs.

**Pull request closed without merging**
