### PR TITLE
[KEYCLOAK-13591] [openshift] Refresh (up2date) various currently invalid (HTTP 404) links

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-13591] [openshift] Refresh (up2date) various currently invalid (HTTP 404) links
    
    Some of OpenShift's guide links got invalidated (HTTP 404 Not Found) after the redesign
    of the official OCP documentation from v3.x to v4.x. Point them back to proper locations
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

### CODE REVIEW

**Comment by iankko** [comment]
@lhanusov @andymunro @hmlnarik @stianst PTAL (once got a chance)

Thanks!, Jan

**Review by lhanusov — COMMENTED** [review]
All new OpenShift documentation links are available and follow the logical context. Also they replace all unavailable old links.

I have a question about ocp311docs_passthrough_route_link and ocp311docs_reencrypt_route_link. There is no latest version of this documentation?

Also in Introduction chapter where you placed: ocp311docs_reencrypt_route_link, there was already working link https://docs.openshift.com/container-platform/4.3/networking/routes/secured-routes.html. Does it mean that it was a wrong link?

**Comment by iankko** [comment]
@lhanusov Thanks for the review, Lukas!

> All new OpenShift documentation links are available and follow the logical context. Also they replace all unavailable old links.

Great!

> 
> I have a question about ocp311docs_passthrough_route_link and ocp311docs_reencrypt_route_link. There is no latest version of this documentation?

Correct. While passthrough / re-encrypt modes are mentioned in latest (v4.3) OCP docs, they are mentioned only marginally IMHO:
* `passthrough` route case:
  * https://docs.openshift.com/container-platform/4.3/scalability_and_performance/routing-optimization.html
  * https://docs.openshift.com/container-platform/4.3/networking/routes/route-configuration.html
* `re-encrypt` route case:
   * https://docs.openshift.com/container-platform/4.3/networking/routes/secured-routes.html
   * https://docs.openshift.com/container-platform/4.3/networking/routes/route-configuration.html

But there doesn't seem to be a page in OCP (v4.3) docs, actually explaining the meaning of the `passthrough / re-encrypt` terms (like it's the case in OCP v3.11 configuration), which could be used to explain the difference between the provided templates for the Red Hat Single Sign-On image (=> I have kept the 3.11 version of those two links).

> 
> Also in Introduction chapter where you placed: ocp311docs_reencrypt_route_link, there was already working link https://docs.openshift.com/container-platform/4.3/networking/routes/secured-routes.html. Does it mean that it was a wrong link?

No, you are correct. That one was working correctly. It got changed solely from the reason the approach to all of the OCP docs links to be consistent (not reference the links in the chapters directly, but rather have one place listing all of them, and let the chapters reference just the asciidoc variables)

**Review by lhanusov — APPROVED** [review]
I agree with all these changes and about links, which are still on OCP 3.11 docs version, I raised a ticket: https://issues.redhat.com/browse/OSDOCS-995. When fixed, it can be updated in RHSSO, but I think, it is ok, to do it in next possible release.

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
