### PR TITLE
Fixing KEYCLOAK-14642

### PR DESCRIPTION
**Pull request by ultimatesecpro**
Fixing documentation to resolve KEYCLOAK-14642

### CODE REVIEW

**Review by mhajas — CHANGES_REQUESTED** [review]
Thank you for the PR @ultimatesecpro. It seems to be wrongly indented though. Could you please indent with 4 spaces instead of tabs?

**Review by ultimatesecpro — COMMENTED** [review]
Change tab to spaces

**Review by mhajas — APPROVED** [review]
Thanks @ultimatesecpro, now it LGTM!

**Review by pedroigor — APPROVED** [review]

**Comment by hmlnarik** [comment]
Travis failures are irrelevant.

**Pull request merged**
