### PR TITLE
Server Development updates - Forward port edits from Downstream MR

### PR DESCRIPTION
**Pull request by andymunro**
See https://issues.redhat.com/browse/CIAM-2488

Close #CIAM-2488

### CODE REVIEW

**Comment by andymunro** [comment]
@nchopra  Can you approve these updates, which match the downstream updates? We need to keep the upstream version synch.

**Comment by andymunro** [comment]
Errors are only for the Product version and only report that the build script cannot find the other guides. The log ends with a success message for all guides.

**Comment by andymunro** [comment]
@mposolda Can you verify these changes to make this match the downstream version?

**Review by mposolda — APPROVED** [review]
@andymunro Thanks for the changes!

**Pull request merged**
