### PR TITLE
KEYCLOAK-6567 configure moved openshift content to our build process

### PR DESCRIPTION
**Pull request by matthewhelmke**
This _almost_ works. I need help figuring out how to fix one build error. @stianst can you please either help or recommend someone to assist?

High level details:
Line 11 of `topics/reference.adoc` includes a link to a file outside of the build location. Fair enough. I can move that file and fix the reference or I can cut/paste the information into `reference.adoc`. 
However, the linked file, `common/maven_mirror_url.adoc`, contains information I don't quite understand and when I do either of these, I have more build errors as the content seems to trigger an attempt to use parts of the old build system.

### CODE REVIEW

**Comment by stianst** [comment]
@matthewhelmke sent a PR to your branch with the fixes here https://github.com/matthewhelmke/keycloak-documentation/pull/1

I moved the maven repo file and deleted the other files as they where not used.

**Comment by matthewhelmke** [comment]
@stianst thank you. Merged it into this.

**Comment by stianst** [comment]
@matthewhelmke can you resolve merge conflicts? @iankko can you review please?

**Comment by stianst** [comment]
Looks good to me, but I'd like @iankko to review it properly

**Comment by iankko** [comment]
@matthewhelmke 
Hey Matt,
     could you bring the image files back? Here's what I get when trying to build this one locally:

```
...
Setting up en-US
	Processing file tmp/en-US/xml/Common_Content/Conventions.xml -> tmp/en-US/xml/Common_Content/Conventions.xml
	Processing file tmp/en-US/xml/Common_Content/Feedback.xml -> tmp/en-US/xml/Common_Content/Feedback.xml
	Processing file tmp/en-US/xml/Common_Content/Legal_Notice.xml -> tmp/en-US/xml/Common_Content/Legal_Notice.xml
	Processing file tmp/en-US/xml/Common_Content/Program_Listing.xml -> tmp/en-US/xml/Common_Content/Program_Listing.xml
	Processing file tmp/en-US/xml/Common_Content/Revision_History.xml -> tmp/en-US/xml/Common_Content/Revision_History.xml
	Processing file tmp/en-US/xml_tmp/Author_Group.xml -> tmp/en-US/xml/Author_Group.xml
	Processing file tmp/en-US/xml_tmp/Revision_History.xml -> tmp/en-US/xml/Revision_History.xml
	Processing file tmp/en-US/xml_tmp/master.xml -> tmp/en-US/xml/master.xml
ERROR: Image missing: tmp/en-US/xml/images/sso_app_jee_jsp.svg
 at /usr/share/perl5/vendor_perl/HTML/Element.pm line 1562.
```

**Comment by matthewhelmke** [comment]
@iankko this current commit builds locally using mvn but not ./build-product.sh. I am not sure why. The commit does fix a couple of bad references to the location of the svn images, which were already present.

I haven't yet looked at the conflicts.

**Comment by matthewhelmke** [comment]
@iankko and @stianst  I have fixed the conflicts and this builds for me using both `mvn` and `./build-product.sh` well, mostly.

With `./build-product.sh`, I still get a "missing image" error for the ccutil build, but the build works perfectly for AsciiDoctor and the image appears when I view the link. I find that confusing.

EDIT: the first link works in the output, the second does not even get built:

```
$ ./build-product.sh openshift/
************************************************************************************************

Building: Red Hat Single Sign-On for OpenShift :xpaasproduct_link: {project_doc_base_url}/openshift/ :xpaasproduct-shortname: RH-SSO for OpenShift

Deleting /home/mhelmke/GitRepos/keycloak-documentation/openshift/build

Running asciidoctor...

Input file: master.adoc
  Time to read and parse source: 0.03455
  Time to convert document: 0.03018
  Total time (read, parse and convert): 0.06473

Running ccutil...

Transforming the AsciiDoc content to DocBook XML...
Setting up en-US
	Processing file tmp/en-US/xml/Common_Content/Conventions.xml -> tmp/en-US/xml/Common_Content/Conventions.xml
	Processing file tmp/en-US/xml/Common_Content/Feedback.xml -> tmp/en-US/xml/Common_Content/Feedback.xml
	Processing file tmp/en-US/xml/Common_Content/Legal_Notice.xml -> tmp/en-US/xml/Common_Content/Legal_Notice.xml
	Processing file tmp/en-US/xml/Common_Content/Program_Listing.xml -> tmp/en-US/xml/Common_Content/Program_Listing.xml
	Processing file tmp/en-US/xml/Common_Content/Revision_History.xml -> tmp/en-US/xml/Common_Content/Revision_History.xml
	Processing file tmp/en-US/xml_tmp/Author_Group.xml -> tmp/en-US/xml/Author_Group.xml
	Processing file tmp/en-US/xml_tmp/Revision_History.xml -> tmp/en-US/xml/Revision_History.xml
	Processing file tmp/en-US/xml_tmp/master.xml -> tmp/en-US/xml/master.xml
ERROR: Image missing: tmp/en-US/xml/../images/sso_app_jee_jsp.svg
 at /usr/share/perl5/vendor_perl/HTML/Element.pm line 1562.

Done

************************************************************************************************

Red Hat Single Sign-On for OpenShift :xpaasproduct_link: {project_doc_base_url}/openshift/ :xpaasproduct-shortname: RH-SSO for OpenShift
 - AsciiDoctor:  file:///home/mhelmke/GitRepos/keycloak-documentation/openshift/target/html/index.html
 - ccutil:       file:///home/mhelmke/GitRepos/keycloak-documentation/openshift/build/tmp/en-US/html-single/index.html

************************************************************************************************
```

**Comment by stianst** [comment]
Sent a new PR with fixing images, adding tests and a few more minor things:
https://github.com/keycloak/keycloak-documentation/pull/396

**Pull request closed without merging**
