### PR TITLE
CIAM-2486 - Upgrading Guide, applying final downstream changes

### PR DESCRIPTION
**Pull request by andymunro**
Several changes were requested in downstream and we need to keep upstream in synch

(cherry picked from commit 696f14f8171a6bb6dbf65ab4d5b75fe1f9fc4587)

### CODE REVIEW

**Comment by andymunro** [comment]
@Aboullos Can you verify this PR for upstream so we keep it in synch?  It is the same changes as in downstream.

**Comment by Aboullos** [comment]
LGTM!

**Comment by andymunro** [comment]
@mposolda Would you be able to approve and merge this PR so we can keep upstream current with downstream changes?

It is approved by @Aboullos  for QE.

**Review by mposolda — APPROVED** [review]
@andymunro LGTM, Thanks

**Comment by andymunro** [comment]
Thanks, @mposolda

**Pull request merged**
