### PR TITLE
[KEYCLOAK-9809] Support private_key_jwt authentication for external IdP

### PR DESCRIPTION
**Pull request by madgaet**

### CODE REVIEW

**Review by mposolda — APPROVED** [review]
@madgaet Thanks!

**Comment by mposolda** [comment]
@andymunro Do you have a chance to review? Thanks!

**Comment by mposolda** [comment]
Implementation PR: https://github.com/keycloak/keycloak/pull/6303

**Comment by roidelapluie** [comment]
this PR can be closed?

**Comment by roidelapluie** [comment]
Which one of the PR is the good one?

**Comment by mposolda** [comment]
@roidelapluie This PR can't be closed. It is the update of the keycloak-documentation, which is required because of the new thing, which will be added in the keycloak codebase in the PR https://github.com/keycloak/keycloak/pull/6303 . Both implementation and documentation PR are needed, no need to close any of them.

**Comment by roidelapluie** [comment]
Oh indeed sorry :)

**Comment by roidelapluie** [comment]
I was confusing with https://github.com/keycloak/keycloak/pull/6269

**Review by andymunro — APPROVED** [review]
You were right, Marek.  It was quick.

**Comment by mposolda** [comment]
@andymunro Thanks!

**Pull request merged**
