### PR TITLE
Example configuration for running as sidecar container in Kubernetes

### PR DESCRIPTION
**Pull request by transducer**

### CODE REVIEW

**Comment by stianst** [comment]
Hi, thanks for your PR and sorry for the late reply. I'm not 100% convinced that it's ideal to provide so much detail in the documentation, would probably think some sort of QuickStart would be better. Maybe we could add a QuickStart around Gatekeeper on https://github.com/keycloak/keycloak-quickstarts including templates for Kube and OpenShift. @abstractj WDYT?

**Comment by abstractj** [comment]
@stianst @transducer a quickstart would be fantastic +1 about it. Often code at the docs get outdated in few month and it's hard to test.

**Review by stianst — CHANGES_REQUESTED** [review]
Documentation shouldn't contain large examples like this, rather we should have a quickstart for Gatekeeper around this.

**Comment by stianst** [comment]
Thanks for the PR, but we are not able to maintain large examples like this within the documentation.

**Pull request closed without merging**
