### PR TITLE
KEYCLOAK-13553 qualifying OpenShift procedure as for 3.x

### PR DESCRIPTION
**Pull request by andymunro**
@mposolda Can you verify this?

### CODE REVIEW

**Review by iankko — CHANGES_REQUESTED** [review]
Don't agree to add this change. All `oc` commands listed in the documentation are universal (not OCP v3.x vs OCP v4.x dependent).

The only needed difference is the expected form oc `oc login` command at the beginning, which is tracked under [KEYCLOAK-13280](https://issues.redhat.com/browse/KEYCLOAK-13280).

This PR should be closed (not needed).

**Comment by mposolda** [comment]
@iankko @lhanusov Should this PR be closed or not? I am not 100% sure as I see that JIRA KEYCLOAK-13280 contains some additional comments even after there was suggestion to close this PR in the comment from MArch 31. If it should be closed, could you please close it?

**Comment by lhanusov** [comment]
@mposolda Yes, you can cancel this PR. @iankko is right that in the Jira ticket it is described more complexly and this PR does not make sense anymore.

**Comment by mposolda** [comment]
@lhanusov Cool, Thanks!

**Pull request closed without merging**
