### PR TITLE
Correct sections order

### PR DESCRIPTION
**Pull request by k-tamura**
Section order (4.3 to 4.5) [in Keycloak Getting Started guide](https://www.keycloak.org/docs/10.0/getting_started/index.html#securing-a-jboss-servlet-application) has been incorrect since version 9.0.

### Before version 8.0
4. Securing a JBoss Servlet Application
    4.1 Before You Start
    4.2 Installing the Client Adapter
    4.3 Downloading, Building, and Deploying Application Code
    4.4 Creating and Registering the Client
    4.5 Configuring the Subsystem

### Version 9.0 (since [this commit](https://github.com/keycloak/keycloak-documentation/commit/eda0215be4ac1de8e9bdef28790ed4a24fa85c39#diff-c41b50e359baf3bca845bee3f9fe5119) -> regression)
4. Securing a JBoss Servlet Application
    4.1 Before You Start
    4.2 Installing the Client Adapter
    4.3 Configuring the Subsystem
    4.4 Downloading, Building, and Deploying Application Code
    4.5 Creating and Registering the Client

### After version 10.0 (since [this commit](https://github.com/keycloak/keycloak-documentation/commit/5ab8c4064ee04e28ee6aa2545790e1c3c297d40b#diff-c41b50e359baf3bca845bee3f9fe5119) -> regression)
4. Securing a JBoss Servlet Application
    4.1 Before You Start
    4.2 Installing the Client Adapter
    4.3 Creating and Registering the Client
    4.4 Configuring the Subsystem
    4.5 Downloading, Building, and Deploying Application Code

### CODE REVIEW

**Comment by k-tamura** [comment]
Please wait a while. I'm reviewing my PR.

**Comment by k-tamura** [comment]
This section has some problems and confuses beginners. So I will do new PR later with the following suggestions:

Suggestion 1: Sections order should be changed to:

- 4.1 Before You Start
- 4.2 Downloading and Starting up WildFly
- 4.3 Downloading, Building, and Deploying Application Code
       (and Testing "vanilla" app without client adapter)
- 4.4 Installing the Client Adapter
- 4.5 Creating and Registering the Client
- 4.6 Configuring the Subsystem
       (and Testing "vanilla" app protected by client adapter)

Suggestion 2: 
"_http://localhost:8180/vanilla_" should be changed to "_http://localhost:8080/vanilla_".

Suggestion 3: 
The BASIC auth login dialog image should be added:
client-auth-required

**Comment by k-tamura** [comment]
I have reviewed/changed my PR and confirmed that it works without any problems. Could you review it?

**Comment by andymunro** [comment]
@stian was the last one to change the sequence of section and he requested the change from 8080 to 8180. Need his input.

**Comment by andymunro** [comment]
@k-tamura The following PR, when approved, will make a number of corrections including the one that pointed out:  https://github.com/keycloak/keycloak-documentation/pull/959

**Comment by k-tamura** [comment]
Okay. Please close this ticket. I will review #959 if I have time.

**Comment by abstractj** [comment]
@k-tamura @andymunro just double checking. Shall we close this PR, assuming that #959 was merged?

**Comment by andymunro** [comment]
Yes #959 was merged and the content uses the same order for sections identified in this PR.

**Comment by abstractj** [comment]
Thanks Andy. @k-tamura closing it as this PR was superseded by #959

**Pull request closed without merging**
