### PR TITLE
Keycloak 7166 documentation of new logout parameter take2

### PR DESCRIPTION
**Pull request by torbjornsk**

### CODE REVIEW

**Comment by torbjornsk** [comment]
Tried running the failed tests locally, SecuringAppsTest only checkExternalLinks failed, without me adding any such links. ServerAdminTest checkExternalLinks also failed, rest is green..

**Review by matthewhelmke — APPROVED** [review]
Thank you, @torbjornsk, this looks good to me.
@mposolda, let's see if we can approve and merge quickly since @torbjornsk did such a good, quick job of resubmitting a clean PR.

**Comment by mposolda** [comment]
@matthewhelmke +1. I would definitely approve this once the codebase PR can be merged as well (the only remaining thing is to have jenkins build passed for the upstream PR).

**Review by mposolda — APPROVED** [review]
@torbjornsk Thanks again for your contribution!

**Pull request merged**
