### PR TITLE
Updating OpenShift guide to match downstream edits

### PR DESCRIPTION
**Pull request by andymunro**
Also, this includes the OpenShift guide and release note updates to remove OpenJ9 references (see https://issues.redhat.com/browse/CIAM-2258)

Closes #CIAM-2504

### CODE REVIEW

**Comment by andymunro** [comment]
@iankko, @kakella. Can you verify these changes to make the upstream match downstream. These are already approved in downstream. In future, we will try to get the final approval in upstream, then submit to downstream.

**Comment by kami619** [comment]
@andymunro my github username is different, so the PR tag was not notified with me, im taking a look at it now.

**Comment by kami619** [comment]
@andymunro there seems to be some broken links as per the CI builds above, not sure if we wanted to address them first

**Review by mposolda — APPROVED** [review]

**Comment by andymunro** [comment]
Thank you @kami619 for the clarification. Thanks for merging @mposolda

**Pull request merged**
