### PR TITLE
Update auth-spi.adoc

### PR DESCRIPTION
**Pull request by jpenren**
Some fixes and minimal code to follow the example

### CODE REVIEW

**Review by matthewhelmke — APPROVED** [review]
This looks good to me. Thank you.

**Comment by stianst** [comment]
Will need someone from engineering to review this one.

**Comment by stianst** [comment]
Putting this on hold for a bit as we are busy with wrapping up 4.x and don't have the capacity to review right now.

**Comment by stianst** [comment]
Closing as I've opened a new PR with merge conflicts resolved here: https://github.com/keycloak/keycloak-documentation/pull/766

**Pull request closed without merging**
