### PR TITLE
KEYCLOAK-19433 Release Note about deprecating Spring Boot adapter.

### PR DESCRIPTION
**Pull request by andymunro**
@hmlnarik Can you approve this change requested by John Doyle?

### CODE REVIEW

**Review by stianst — CHANGES_REQUESTED** [review]
This is being added to the release notes of the previous release, and not the most release. I'm also not sure if the release notes are the best place for this notice as I would imagine people read those when they upgrade and do not return to these.

**Comment by andymunro** [comment]
@stianst I added a note to the securing apps guide also.  This upstream PR is for 7.4.10, but I will clone it for 7.5.1.

**Comment by stianst** [comment]
I would just change this PR to only cover 7.5. I don't think we should be adding deprecating notes to a version that is pretty much out of support anyways. However, if you think we should add it to both, then a single PR updating both 7.4 and 7.5 release notes would be better here.

**Comment by andymunro** [comment]
Thanks, @stianst I can use one PR for upstream but I will first need these clones of downstream 7.5 PRs forward ported to upstream:

- https://github.com/keycloak/keycloak-documentation/pull/1264 (Release Notes)
- https://github.com/keycloak/keycloak-documentation/pull/1260 (Securing Apps)
This is for 7.5.1 which has a code freeze on Friday 11/5.

**Review by stianst — APPROVED** [review]

**Pull request merged**
