### PR TITLE
chore: added docs for PayPal social login

### PR DESCRIPTION
**Pull request by petlys**
Documentation related to PR https://github.com/keycloak/keycloak/pull/4449

### CODE REVIEW

**Comment by stianst** [comment]
Could you move paypal-add-identity-provider.png to keycloak-images as it's using the Keycloak theme.

**Comment by petlys** [comment]
> Could you move paypal-add-identity-provider.png to keycloak-images as it's using the Keycloak theme.

Done 👍

**Comment by petlys** [comment]
Updated to accommodate changes in https://github.com/keycloak/keycloak/pull/4449

**Comment by petlys** [comment]
Tests run fine locally. Don't get why they fail on travis

**Comment by stianst** [comment]
Tests are broken because they are already broken in master due to some missing images, so not your fault. I'll crop the image to remove the menu though so it can be used both for Keycloak and RH-SSO.

**Comment by stianst** [comment]
Closing PR. Opened a new PR with cropped image https://github.com/keycloak/keycloak-documentation/pull/199

**Pull request closed without merging**
