### PR TITLE
[KEYCLOAK-6116] - Reference to Subject Email using Subject Alternative Name

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Review by matthewhelmke — DISMISSED** [review]
Looks good to me.

**Comment by vmuzikar** [comment]
@pedroigor Do you think we should explicitly mention the email's extracted the "rfc822Name" field of the SAN extension since there are other SAN fields as well?

**Comment by pedroigor** [comment]
@vmuzikar, I'm not sure the name of the identity source is clearly stating that the email is extracted using the SAN extension ...

But if you think we should have it, I'm OK to include it ....

**Comment by pedroigor** [comment]
@vmuzikar, done.

**Comment by vmuzikar** [comment]
@pedroigor Thanks! I believe this makes it clear now.

**Review by matthewhelmke — APPROVED** [review]

**Comment by pedroigor** [comment]
@matthewhelmke, code already pushed to repository. Can we have this change in ?

**Pull request merged**
